DETECTOR_FULL_NAMES = {
    'hrc'                                       : 'High Resolution Channel (HRC)',
    'sbn'                                       : 'Solar Blind Channel (SBN)',
    'wfc'                                       : 'Wide Field Channel (WFC)',
    'uvis'                                      : 'Ultraviolet and Visual Channel',
    'ir'                                        : 'Infrared Channel',
    'imaging science subsystem - narrow angle'  : 'Narrow Angle Camera',
    'imaging science subsystem - wide angle'    : 'Wide Angle Camera',
    'iss - narrow angle'                        : 'Narrow Angle Camera',
    'iss - wide angle'                          : 'Wide Angle Camera',
    'mdis - narrow angle'                       : 'Narrow Angle Camera',
    'mdis - wide angle'                         : 'Wide Angle Camera',
    'mercury dual imaging system - narrow angle': 'Narrow Angle Camera',
    'vg iss - narrow angle'                     : 'Narrow Angle Camera',
    'vg iss - wide angle'                       : 'Wide Angle Camera',
    'optical microscope'                        : 'Optical Microscope',
}
