HOST_FROM_INSTRUMENT = {
    'acrim 3'   : 'Active Cavity Irradiance Monitor Satellite (AcrimSat)',
    'acs'       : 'Hubble Space Telescope (HST)',
    'alma'      : 'Atacama Large Millimeter/submillimeter Array (ALMA)',
    'asi/met'   : 'Mars Pathfinder Lander',
    'aster'     : 'Terra',
    'apxs'      : 'Curiosity Rover',
    'cda'       : 'Cassini Orbiter',
    'cfht'      : 'Canada-France-Hawaii Telescope (CFHT)',
    'chemcam'   : 'Curiosity Rover',
    'chemin'    : 'Curiosity Rover',
    'chimra'    : 'Curiosity Rover',
    'cirs'      : 'Cassini Orbiter',
    'civa'      : 'Philae Lander',
    'crism'     : 'Mars Reconnaissance Orbiter (MRO)',
    'ctx'       : 'Mars Reconnaissance Orbiter (MRO)',
    'dan'       : 'Dynamic Albedo of Neutrons (DAN)',
    'disr'      : 'Huygens Probe',
    'foc'       : 'Hubble Space Telescope (HST)',
    'grns'      : 'MESSENGER',
    'grs'       : '2001 Mars Odyssey',
    'hazcam'    : ['Spirit (MER-A)', 'Opportunity (MER-B)', 'Curiosity Rover'],
    'hirise'    : 'Mars Reconnaissance Orbiter (MRO)',
    'hri'       : 'Deep Impact',
    'hrsc'      : 'Mars Express',
    'imp'       : 'Mars Pathfinder Lander',
    'irac'      : 'Spitzer Telescope',
    'irs'       : 'Spitzer Telescope',
    'iss'       : ['Voyager 1', 'Voyager 2', 'Cassini Orbiter'],
    'irtf'      : 'Infrared Telescope Facility (IRTF)',
    'inms'      : 'Cassini Orbiter',
    'jiram'     : 'Juno',
    'junocam'   : 'Juno',
    'leisa'     : 'New Horizons',
    'lorri'     : 'New Horizons',
    'mahli'     : 'Curiosity Rover',
    'marci'     : 'Mars Reconnaissance Orbiter (MRO)',
    'marie'     : '2001 Mars Odyssey',
    'marsis'    : 'Mars Express',
    'marvel'    : 'Mars Scout',
    'mascs'     : 'MESSENGER',
    'mastcam'   : 'Curiosity Rover',
    'mdis'      : 'MESSENGER',
    'meca'      : 'Phoenix Mars Lander',
    'met'       : 'Phoenix Mars Lander',
    'mb'        : ['Spirit (MER-A)', 'Opportunity (MER-B)'],
    'mi'        : ['Spirit (MER-A)', 'Opportunity (MER-B)'],
    'mini-tes'  : ['Spirit (MER-A)', 'Opportunity (MER-B)'],
    'miro'      : 'Rosetta Orbiter',
    'misr'      : 'Terra',
    'mla'       : 'MESSENGER',
    'moc'       : 'Mars Global Surveyor (MGS)',
    'mri'       : 'Deep Impact',
    'mola'      : 'Mars Global Surveyor (MGS)',
    'msi'       : 'NEAR Shoemaker',
    'mvic'      : 'New Horizons',
    'navcam'    : ['Curiosity Rover', 'Rosetta Orbiter'],
    'ngims'     : 'Mars Atmosphere and Volatile Evolution (MAVEN)',
    'nicmos'    : 'Hubble Space Telescope (HST)',
    'nims'      : 'Galileo Orbiter',
    'nis'       : 'NEAR Shoemaker',
    'nlr'       : 'NEAR Shoemaker',
    'omega'     : 'Mars Express',
    'osiris'    : 'Rosetta Orbiter',
    'pancam'    : ['Spirit (MER-A)', 'Opportunity (MER-B)'],
    'pps'       : ['Voyager 1', 'Voyager 2'],
    'rad'       : 'Curiosity Rover',
    'ralph'     : 'New Horizons',
    'rems'      : 'Curiosity Rover',
    'rex'       : 'New Horizons',
    'rolis'     : 'Philae Lander',
    'rss'       : ['Voyager 1', 'Voyager 2', 'Cassini Orbiter'],
    'sam'       : 'Curiosity Rover',
    'sharad'    : 'Mars Reconnaissance Orbiter (MRO)',
    'swap'      : 'New Horizons',
    'tega'      : 'Phoenix Mars Lander',
    'tes'       : 'Mars Global Surveyor (MGS)',
    'themis'    : '2001 Mars Odyssey',
    'trappist'  : 'Transiting Planets and Planetesimals Small Telescope (TRAPPIST)',
    'uvis'      : 'Cassini Orbiter',
    'uvs'       : ['Voyager 1', 'Voyager 2'],
    'vims'      : 'Cassini Orbiter',
    'virtis'    : ['Rosetta Orbiter', 'Venus Express'],
    'wfc3'      : 'Hubble Space Telescope (HST)',
    'wfpc2'     : 'Hubble Space Telescope (HST)',
    'xrs'       : 'MESSENGER',

    'alice ultraviolet spectrometer': 'New Horizons',
    'wise telescope'                : 'WISE',
    'moon mineralogy mapper'        : 'Chandrayaan-1',
    'hubble space telescope'        : 'Hubble Space Telescope (HST)',
    'framing camera'                : 'Dawn',
    'samuel oschin telescope'       : 'Palomar Observatory',
    'arecibo radar'                 : 'Arecibo Observatory',
    'photopolarimeter/radiometer'   : 'Galileo Orbiter',
    'gemini north telescope'        : 'Gemini North Telescope',
    'gemini south telescope'        : 'Gemini South Telescope',
    'hale telescope'                : 'Palomar Observatory',
    'keck telescope'                : 'W. M. Keck Telescope',
    'w. m. keck telescope'          : 'W. M. Keck Telescope',
    'solid state imaging (ssi)'     : 'Galileo Orbiter',
    'surface stereo imager (ssi)'   : 'Phoenix Mars Lander',
    'neocam sensor'                 : 'Near-Earth Object Camera (NEOCam)',
}
