INSTRUMENT_FULL_NAMES = {
    'acs'       : 'Advanced Camera for Surveys (ACS)',
    'alice uvs' : 'Alice Ultravilet Spectrometer',
    'alice'     : 'Alice Ultravilet Spectrometer',
    'apxs'      : 'Alpha Particle X-Ray Spectrometer (APXS)',
    'aster'     : 'Advanced Spaceborne Thermal Emission and Reflection Radiometer (ASTER)',
    'cda'       : 'Cosmic Dust Analzer (CDA)',
    'cfht'      : 'Canada-France-Hawaii Telescope (CFHT)',
    'chemcam'   : 'Chemistry & Camera (ChemCam)',
    'chemin'    : 'Chemistry & Mineralogy X-Ray Diffraction (CheMin)',
    'chimera'   : 'Collection and Handling for Interior Martian Rock Analysis (CHIMRA)',
    'chimra'    : 'Collection and Handling for Interior Martian Rock Analysis (CHIMRA)',
    'cirs'      : 'Composite Infrared Spectrometer (CIRS)',
    'civa'      : 'Comet Infrared and Visible Analyser (CIVA)',
    'crism'     : 'Compact Reconnaissance Imaging Spectrometer for Mars (CRISM)',
    'ctx'       : 'Context Camera (CTX)',
    'dan'       : 'Dynamic Albedo of Neutrons (DAN)',
    'epps'      : 'Energetic Particle and Plasma Spectrometer (EPPS)',
    'fips'      : 'Fast Imaging Plasma Spectrometer (FIPS)',
    'foc'       : 'Faint Object Camera (FOC)',
    'grns'      : 'Gamma-Ray and Neutron Spectrometer (GRNS)',
    'grs'       : 'Gamma Ray Spectrometer (GRS)',
    'hazcam'    : 'Hazard Camera (Hazcam)',
    'hirise'    : 'High Resolution Imaging Science Experiment (HiRISE)',
    'hri'       : 'High Resolution Instrument (HRI)',
    'hrsc'      : 'High Resolution Stereo Camera (HRSC)',
    'inms'      : 'Ion and Neutral Mass Spectrometer (INMS)',
    'irac'      : 'Infrared Array Camera (IRAC)',
    'irs'       : 'Infrared Spectrograph (IRS)',
    'irtf'      : 'Infrared Telescope Facility (IRTF)',
    'iss'       : 'Imaging Science Subsystem (ISS)',
    'jiram'     : 'Juno Infrared Auroral Mapper (JIRAM)',
    'leisa'     : 'Linear Etalon Imaging Spectral Array (LEISA)',
    'lorri'     : 'Long Range Reconnaissance Imager (LORRI)',
    'lvs'       : 'Lander Vision System (LVS)',
    'mag'       : 'Magnetometer',
    'mahli'     : 'Mars Hand Lens Imager (MAHLI)',
    'marci'     : 'Mars Color Imager (MARCI)',
    'mardi'     : 'Mars Descent Imager (MARDI)',
    'marie'     : 'Mars Radiation Environment Experiment (MARIE)',
    'marsis'    : 'Mars Advanced Radar for Subsurface and Ionosphere Sounding (MARSIS)',
    'mascs'     : 'Mercury Atmospheric and Surface Composition Spectrometer (MASCS)',
    'mastcam'   : 'Mast Camera (MastCam)',
    'meca'      : 'Microscopy, Electrochemistry, and Conductivity Analyzer (MECA)',
    'met'       : 'Meteorological Station (MET)',
    'mimi'      : 'Magnetospheric Imaging Instrument (MIMI)',
    'miro'      : 'Microwave Instrument for the Rosetta Orbiter (MIRO)',
    'mini-tes'  : 'Miniature Thermal Emission Spectrometer (Mini-TES)',
    'misr'      : 'Multi-Angle Imaging SpectroRadiometer (MISR)',
    'mla'       : 'Mercury Laser Altimeter (MLA)',
    'mola'      : 'Mars Orbiter Laser Altimeter (MOLA)',
    'mvic'      : 'Multispectral Visible Imaging Camera (MVIC)',
    'mwr'       : 'Microwave Radiometer (MWR)',
    'navcam'    : 'Navigation Camera (Navcam)',
    'nicmos'    : 'Near Infrared Camera and Multi-Object Spectrometer (NICMOS)',
    'ngims'     : 'Neutral Gas and Ion Mass Spectrometer (NGIMS)',
    'nis'       : 'Near-Infrared Spectrometer (NIS)',
    'nlr'       : 'NEAR Laser Rangefinder (NLR)',
    'omega'     : 'Visible and Infrared Mineralogical Mapping Spectrometer (OMEGA)',
    'osiris'    : 'Optical, Spectrocopic and Infrared Remote Imaging System (OSIRIS)',
    'pancam'    : 'Panoramic Camera (Pancam)',
    'pps'       : 'Photopolarimeter Subsystem (PPS)',
    'rad'       : 'Radiation Assessment Detector (RAD)',
    'ralph'     : 'Visible/Infrared Imager (RALPH)',
    'rems'      : 'Rover Environmental Monitoring Station (REMS)',
    'rex'       : 'Radio Science Experiment (REX)',
    'rolis'     : 'Rosetta Lander Imaging System (ROLIS)',
    'rss'       : 'Radioscience Subsystem (RSS)',
    'sam'       : 'Sample Analysis at Mars (SAM)',
    'ssi'       : 'Solid-State Imaging (SSI)',
    'swap'      : 'Solar Wind Around Pluto (SWAP)',
    'tega'      : 'Thermal and Evolved Gas Analyzer (TEGA)',
    'themis'    : 'Thermal Emission Imaging System (THEMIS)',
    'trappist'  : 'Transiting Planets and Planetesimals Small Telescope (TRAPPIST)',
    'uvis'      : 'Ultraviolet Imaging Spectrometer (UVIS)',
    'uvs'       : 'Ultraviolet Spectrometer (UVS)',
    'vims'      : 'Visual and Infrared Mapping Spectrometer (VIMS)',
    'vir'       : 'Visible and Infrared Spectrometer (VIR)',
    'virtis'    : 'Visible and Infrared Thermal Imaging Spectrometer (VIRTIS)',
    'wfc3'      : 'Wide Field Camera 3 (WFC3)',
    'wfcp3'     : 'Wide Field Camera 3 (WFC3)',
    'wfpc2'     : 'Wide Field/Planetary Camera 2 (WFPC2)',
    'xrs'       : 'X-Ray Spectrometer (XRS)',

    'advanced camera for surveys'               : 'Advanced Camera for Surveys (ACS)',
    'comet infrared and visible analyser (civa' : 'Comet Infrared and Visible Analyser (CIVA)',
    'context camera'                            : 'Context Camera (CTX)',
    'composite infrared spectrometer'           : 'Composite Infrared Spectrometer (CIRS)',
    'cosmic dust analyzer'                      : 'Cosmic Dust Analyzer (CDA)',
    'descent imager/spectral radiometer'        : 'Descent Imager/Spectral Radiometer (DISR)',
    'faint object camera'                       : 'Faint Object Camera (FOC)',
    'imager for mars pathfinder'                : 'Imager for Mars Pathfinder (IMP)',
    'imaging radar'                             : 'RADAR',
    'imaging science subsystem - narrow angle'  : 'Imaging Science Subsystem (ISS)',
    'imaging science subsystem - wide angle'    : 'Imaging Science Subsystem (ISS)',
    'imaging science subsystem'                 : 'Imaging Science Subsystem (ISS)',
    'imaging science subsystem'                 : 'Imaging Science Subsystem (ISS)',
    'imaging ultraviolet spectrograph'          : 'Imaging Ultraviolet Spectrograph (IUVS)',
    'ion and neutral mass spectrometer'         : 'Ion and Neutral Mass Spectrometer (INMS)',
    'iss - narrow angle'                        : 'Imaging Science Subsystem (ISS)',
    'iss - wide angle'                          : 'Imaging Science Subsystem (ISS)',
    'low-energy charged particle instrument'    : 'Low-Energy Charged Particle Instrument (LECP)',
    'mdis - narrow angle'                       : 'Mercury Dual Imaging System (MDIS)',
    'mdis - wide angle'                         : 'Mercury Dual Imaging System (MDIS)',
    'mercury dual imaging system - narrow angle': 'Mercury Dual Imaging System (MDIS)',
    'mercury dual imaging system'               : 'Mercury Dual Imaging System (MDIS)',
    'multi-spectral imager'                     : 'Multi-Spectral Imager (MSI)',
    'near infrared camera'                      : 'Imaging Science Subsystem (ISS)',
    'near infra-red mapping spectrometer'       : 'Near Infrared Mapping Spectrometer (NIMS)',
    'near infrared mapping spectrometer'        : 'Near Infrared Mapping Spectrometer (NIMS)',
    'neowise telescope'                         : 'WISE Telescope',
    'photopolarimeter subsystem'                : 'Photopolarimeter Subsystem (PPS)',
    'plasma wave instrument'                    : 'Plasma Wave Instrument (PWS)',
    'radar mapper'                              : 'RADAR',
    'radio and plasma wave science instrument'  : 'Radio and Plasma Wave Science Instrument (RPWS)',
    'radio science subsystem'                   : 'Radio Science Subsystem (RSS)',
    'ralph color imager'                        : 'Multispectral Visible Imaging Camera (MVIC)',
    'solid state imaging'                       : 'Solid State Imaging (SSI)',
    'solid-state imaging'                       : 'Solid-State Imaging (SSI)',
    'thermal emission imaging system'           : 'Thermal Emission Imaging System (THEMIS)',
    'thermal emission spectrometer'             : 'Thermal Emission Spectrometer (TES)',
    'trace gas orbiter'                         : 'ExoMars Trace Gas Orbiter',
    'ultraviolet imaging spectrograph'          : 'Ultraviolet Imaging Spectrometer (UVIS)',
    'vg imaging science subsystem'              : 'Imaging Science Subsystem (ISS)',
    'vg iss - narrow angle'                     : 'Imaging Science Subsystem (ISS)',
    'vg iss - wide angle'                       : 'Imaging Science Subsystem (ISS)',
    'visual and infrared mapping spectrometer'  : 'Visual and Infrared Mapping Spectrometer (VIMS)',
    'wise'                                      : 'WISE Telescope',
    'alpha particle x-ray spectrometer (msl)'   : 'Alpha Particle X-Ray Spectrometer (APXS)',
    'alpha particle x-ray spectrometer'         : 'Alpha Particle X-Ray Spectrometer (APXS)',
    'high resolution stereo camera'             : 'High Resolution Stereo Camera (HRSC)',
    'hazcam (msl)'                              : 'Hazcam',
    'mars advanced radar for subsurface and ionospheric sounding'
                                                : 'Mars Advanced Radar for Subsurface and Ionosphere Sounding (MARSIS)',
    'mars orbiter camera'                       : 'Mars Orbiter Camera (MOC)',
    'mars orbiter camer'                        : 'Mars Orbiter Camera (MOC)',
    'mars orbiter laser altimeter'              : 'Mars Orbiter Laser Altimeter (MOLA)',
    'navcam (msl)'                              : 'Navcam',
    'robotic arm (msl)'                         : 'Robotic Arm',
    'spizter space telescope'                   : 'Spitzer Space Telescope',
    'thermal emission imaging system'           : 'Thermal Emission Imaging System (THEMIS)',
    'multi-angle imaging spectroradiometer'     : 'Multi-Angle Imaging SpectroRadiometer (MISR)',
    'mercury dual imaging system - wide angle'  : 'Mercury Dual Imaging System (MDIS)',
    'messenger magnetometer (mag)'              : 'Magnetometer',
    'alpha particle x-ray spectrometer'         : 'Alpha Particle X-Ray Spectrometer (APXS)',
    'gamma ray spectrometer suite'              : 'Gamma Ray Spectrometer (GRS)',
    'gamma ray spectrometer'                    : 'Gamma Ray Spectrometer (GRS)',
    'mars descent imager'                       : 'Mars Descent Imager (MARDI)',
    'navigation camera'                         : 'Navigation Camera (Navcam)',
    'panoramic camera'                          : 'Panoramic Camera (Pancam)',
    'hazcam (msl)'                              : 'Hazard Camera (Hazcam)',
    'hazarc camera'                             : 'Hazard Camera (Hazcam)',
    'visible and infrared mineralogical mapping spectrometer'
                                                : 'Visible and Infrared Mineralogical Mapping Spectrometer (OMEGA)',
    'dynamic albedo of neutrons'                : 'Dynamic Albedo of Neutrons (DAN)',
    'rosetta navcam'                            : 'Navigation Camera (Navcam)',
    'oschin schmidt telescope'                  : 'Samuel Oschin Telescope',
    'hazcam (msl)'                              : 'Hazard Camera (Hazcam)',
    'radar mapper'                              : 'RADAR',
    'arecibo observatory'                       : 'Arecibo Radar',
    'arecibo radar data'                        : 'Arecibo Radar',
    'atmospheric structure / meteorology instrument'
                                                : 'Atmospheric Structure Instrument/Meteorology Package (ASI/MET)',
    'keck telescope'                            : 'W. M. Keck Telescope',
    'hale telescope 200-inch'                   : 'Hale Telescope',
    'vlt'                                      : 'Very Large Telescope (VLT)',
    'acrim3'                                    : 'Active Cavity Irradiance Monitor 3 (ACRIM 3)',
    'radio telescope'                           : 'Arecibo Radar',
    'mars radiation experiment'                 : 'Mars Radiation Environment Experiment (MARIE)',
    'neutron spectrometer'                      : 'Gamma Ray Spectrometer (GRNS)',
    'gamma ray spectrometer - neutron spectrometer'
                                                : 'Gamma Ray Spectrometer (GRS)',
    'laser altimeter'                           : 'Mars Orbiter Laser Altimeter (MOLA)',
    'robotic arm camera'                        : 'Robotic Arm Camera (RAC)',
    'robotic arm'                               : 'Robotic Arm',
    'surface stereo imager'                     : 'Surface Stereo Imager (SSI)',
    'surface stereo imager (ssi)'               : 'Surface Stereo Imager (SSI)',
    'solid state imaging'                       : 'Solid State Imaging (SSI)',
    'solid state imaging (ssi)'                 : 'Solid State Imaging (SSI)',
    'optical microscope'                        : 'Microscopy, Electrochemistry, and Conductivity Analyzer (MECA)',
    'thermal and electrical conductivity probe' : 'Thermal and Electrical Conductivity Probe (TECA)',
    'radio science'                             : 'Radio Science (RS)',
    'magnetometer (mag)'                        : 'Magnetometer',
    'laser rangefinder'                         : 'NEAR Laser Rangefinder (NLR)',
    'near infrared spectrometer'                : 'Near-Infrared Spectrometer (NIS)',
    'neutral gas and ion mass spectrometer'     : 'Neutral Gas and Ion Mass Spectrometer (NGIMS)',
    'radar system'                              : 'RADAR',
    'miniature thermal emission spectrometer'   : 'Miniature Thermal Emission Spectrometer (Mini-TES)',
    'moessbauer spectrometer'                   : 'Moessbauer Spectrometer (MB)',
    'microscopic imager'                        : 'Microscopic Imager (MI)',
    'deep space network'                        : 'Deep Space Network (DSN)',
    'dsn'                                       : 'Deep Space Network (DSN)',
    'navcam (msl)'                              : 'Navigation Camera (Navcam)',
    'plasma spectrometer'                       : 'Radio and Plasma Wave Science Instrument (RPWS)',
    'dual technique magnetometer'               : 'Magnetometer',
    'synthetic-aperture radar (sar)'            : 'RADAR',
}
