MISSION_FROM_HOST = {
    'Cassini Orbiter'           : ('Cassini-Huygens', 'Orbiter'),
    'Huygens Probe'             : ('Cassini-Huygens', 'Probe'),
    'Philae Lander'             : ('Rosetta', 'Lander'),
    'Voyager 1'                 : ('Voyager', 'Flyby Spacecraft'),
    'Voyager 2'                 : ('Voyager', 'Flyby Spacecraft'),
    'Curiosity Rover'           : ('Mars Science Laboratory (MSL)', 'Rover'),
    'Phoenix Mars Lander'       : ('Phoenix', 'Lander'),
    'Rosetta Orbiter'           : ('Rosetta', 'Orbiter'),
    'Mars Pathfinder Lander'    : ('Mars Pathfinder (MPF)', 'Lander'),
    'Mars Pathfinder Rover'     : ('Mars Pathfinder (MPF)', 'Rover'),
    'Galileo Orbiter'           : ('Galileo', 'Orbiter'),
    'Galileo Probe'             : ('Galileo', 'Probe'),
    'Clementine 1'              : ('LCROSS', 'Orbiter'),
    'Viking 1 Orbiter'          : ('Viking', 'Orbiter'),
    'Viking 1 Lander'           : ('Viking', 'Lander'),
    'Viking 2 Orbiter'          : ('Viking', 'Orbiter'),
    'Viking 2 Lander'           : ('Viking', 'Lander'),
    'Viking Orbiter'            : ('Viking', 'Orbiter'),
    'Viking Lander'             : ('Viking', 'Lander'),
    'Gemini North Telescope'    : ('Gemini North Telescope', 'Ground-Based Telescope'),
    'Mariner 1'                 : ('Mariner', 'Flyby Spacecraft'),
    'Mariner 2'                 : ('Mariner', 'Flyby Spacecraft'),
    'Mariner 3'                 : ('Mariner', 'Flyby Spacecraft'),
    'Mariner 4'                 : ('Mariner', 'Flyby Spacecraft'),
    'Mariner 5'                 : ('Mariner', 'Flyby Spacecraft'),
    'Mariner 6'                 : ('Mariner', 'Flyby Spacecraft'),
    'Mariner 7'                 : ('Mariner', 'Flyby Spacecraft'),
    'Mariner 8'                 : ('Mariner', 'Flyby Spacecraft'),
    'Mariner 9'                 : ('Mariner', 'Flyby Spacecraft'),
    'Mariner 10'                : ('Mariner', 'Flyby Spacecraft'),
    'Pioneer 6'                 : ('Pioneer', 'Flyby Spacecraft'),
    'Pioneer 7'                 : ('Pioneer', 'Flyby Spacecraft'),
    'Pioneer 8'                 : ('Pioneer', 'Flyby Spacecraft'),
    'Pioneer 9'                 : ('Pioneer', 'Flyby Spacecraft'),
    'Pioneer 10'                : ('Pioneer', 'Flyby Spacecraft'),
    'Pioneer 11'                : ('Pioneer', 'Flyby Spacecraft'),
    'Surveyor 1'                : ('Surveyor', 'Lander'),
    'Surveyor 2'                : ('Surveyor', 'Lander'),
    'Surveyor 3'                : ('Surveyor', 'Lander'),
    'Surveyor 4'                : ('Surveyor', 'Lander'),
    'Surveyor 5'                : ('Surveyor', 'Lander'),
    'Surveyor 6'                : ('Surveyor', 'Lander'),
    'Surveyor 7'                : ('Surveyor', 'Lander'),
    'Spirit (MER-A)'            : ('Mars Exploration Rover (MER)', 'Rover'),
    'Opportunity (MER-B)'       : ('Mars Exploration Rover (MER)', 'Rover'),
    'Mars Global Surveyor (MGS)': ('Mars Global Surveyor (MGS)', 'Orbiter'),
    'Mars Volcanic Emission Life Scout (MARVEL)'
                                : ('Mars Scout', 'Orbiter'),
    'Mars Helicopter'           : ('Mars 2020 Rover', 'Flier'),
    'Xombie'                    : ('Mars 2020 Rover', 'Rover'),
    'Arecibo Observatory'       : ('Arecibo Observatory', 'Ground-Based Observatory'),
    'W. M. Keck Observatory'    : ('W. M. Keck Observatory', 'Ground-Based Telescope'),
    'Keck 1 Telescope'          : ('W. M. Keck Observatory', 'Ground-Based Telescope'),
    'Keck 2 Telescope'          : ('W. M. Keck Observatory', 'Ground-Based Telescope'),
    'Hubble Space Telescope (HST)'
                                : ('Hubble Space Telescope (HST)', 'Orbiting Telescope'),
    'Infrared Telescope Facility (IRTF)'
                                : ('Infrared Telescope Facility (IRTF)', 'Ground-Based Telescope'),
    'Subaru Telescope'          : ('Subaru Telescope', 'Ground-Based Telescope'),
    'Siding Spring Observatory (SDO)'
                                : ('Siding Spring Observatory (SDO)', 'Ground-Based Telescope'),
    'Kepler'                    : ('Kepler', 'Orbiting Telescope'),
}
