BACKGROUND_STRINGS = [
    "The Jet Propulsion Laboratory's Mars Surveyor Operations Project operates",
    "for details on crediting THEMIS images",
    "For more information about the mission, go to",
    "For more information about MAVEN, visit",
    "For more information about Opportunity, visit",
    "NASA managers have decided to suspend",
    "The Cassini spacecraft ended its mission on",
    "To see updates on the efforts to free the Spirit rover",
    "JunoCam's raw images are available at",
    "For more information:",
    "More information about NASA's Lunar Reconnaissance Orbiter",
    "For more information about exoplanets",
    "For additional information about exoplanets",
    "For more information about InSight",
    "For more information about the mission",
    "For more information about the Mars Science",
    "Other imagery related to these new findings from the Mars",
    "For more information about Europa",
    "For more information about the Dawn mission",
    "For more information about the Spitzer",
    "The RoboSimian team is led by JPL",
#     "has not been radiometrically nor geometrically calibrated",
    "The MESSENGER spacecraft is the first ever to orbit the planet Mercury",
    "The final data transmission received from Pathfinder",
    "With its 14 spectral bands from the visible to the thermal infrared",
    "For a complete list of Dawn mission participants, visit",
    "JunoCam's raw images are available at"
    "For more information on the U.S. instruments aboard Rosetta",
    "was built jointly by JPL and NASA",
    "Aquarius will provide new insights",
    "camera was built by",
    "was built in Japan",
    "was built by Japan",
    "For more information, about the Cassini",
    "JPL hosts the Center for",
    "is a facility of the National Science",
    "For more information on Aura",
    "will provide global color and stereo coverage"
    "Astronomers study weather phenomena on other planets",
    "funds the LDSD mission",
#     "The Cassini orbiter has revealed many surprises",
    "NASA Astrobiology Institute",
    "SIR-C was developed by NASA's Jet Propulsion Laboratory",
    "For information regarding the use of images, see the MESSENGER",
    "For more information on the Kepler",
    "is managed by NASA",
    "is managed by the Jet",
    "Mariner 9 was launched on",
    "is sponsored by NASA",
    "For more information on AVIRIS-NG",
    "For details about the DARPA Robotics",
    "Ceres has an average diameter of about",
    "manages JPL for NASA",
#     "NASA will launch",
    "For more information on these images",
#     "slated for launch in",
    "Spirit has been analyzing",
    "are collaborating on proposals for",
    "UAVSAR is part of NASA",
    "Names shown on the globe are approved by",
    "For information about the Galaxy Evolution Explorer",
    "Juno's primary goal is to ",
    "More information for WISE is",
    "For more information on the Hubble Space Telescope",
    "The Gravity Recovery and Interior Laboratory (GRAIL) mission utilizes",
    "instrument is managed by NASA",
    "is managed for NASA",
    "The WISE spacecraft was put into hibernation"
    "managed by JPL",
#     "Opportunity landed on",
#     "For more information:",
#     "please visit",
    "is an international endeavor with",
    "More information about Rosetta is available",
    "The probe is part of Phoenix",
#     "These images were acquired by the Mars Orbiter Camera",
    "NASA detects, tracks and characterizes ",
#     "These images were prepared by",
    "The MESSENGER spacecraft is the first",
    "The Galaxy Evolution Explorer launched on",
    "is managed by Caltech",
#     "has been prepared for launch"
    "is on course to reach",
    "instrument was built by",
    "mission is a joint project between",
    "For images and more information about Hubble",
    "For more information on GRACE-FO",
    "are currently integrated aboard",
    "provided the helicopter",
    "For more information on AIRS",
    "The TLS technology from Curiosity",
    "was developed jointly by NASA",
    "Complete HiRISE image products are available at",
    "Curiosity is the centerpiece of NASA",
    "During its flight, the Galileo spacecraft",
    "aims to understand the origin and evolution of",
    "manages the Galileo mission",
    "manages the InSight Project",
    "Discovery Program of competitively selected missions",
    "The spacecraft has been orbiting Mars since",
    "Please see the THEMIS Data Citation Note",
    "GRAIL's prime and extended science missions",
    "MISR views Earth with nine cameras",
#     "MISR observes the daylit Earth",
    "More information about the Diviner instrument",
    "for details on crediting THEMIS images",
#     "this THEMIS visual image has not been radiometrically",
    "The main purpose of Curiosity's MAHLI camera is",
    "Mars Global Surveyor entered Mars orbit on Thursday",
    "For information about NASA and agency programs on the Web",
    "With its 14 spectral bands from the visible to the thermal infrared",
    "The Mars Science Laboratory spacecraft is being prepared for launch",
    "JPL is a division of the Caltech in Pasadena, California."
    "information about the Mars Reconnaissance Orbiter are available online at",
    "For information about NASA and agency programs on the Web",
    "For more information on the Kepler and the K2 mission",
    "ChemCam was conceived, designed and built",
    "The KidSat pilot program is sponsored",
    "The website formerly known as KidSat was renamed",
    "More information about the Kepler mission is at",
    "Mariner 9 was launched on May 30",
    "More information can be found on the Deep Space 1 home page",
    "CRISM's mission: Find the spectral",
    "Scientists will use the images to study",
    "NEOWISE originated as a mission called WISE",
    "With its 14 spectral bands from the visible to",
    "about the Cassini-Huygens mission visit",
    "For a complete list of Dawn mission participants",
    "is a mission of the European Space Agency",
    "More on NASA's hurricane research",
#     "Researchers have been using ",
    "developed the DAN instrument",
    "completed its three-month prime mission",
    "More information about NASA's Space Communications",
    "Deep Space 1 completed its primary mission",
#     "team at NASA",
    "More information about Rosetta",
    "information on the GRACE mission is online",
    "is led by Sally",
    "A joint effort between",
    "managed by JPL",
    "is a collaborative endeavor involving",
    "Dawn entered orbit around Vesta on",
    "Ranger 7 was launched",
    "is managing the overall",
    "This image was produced by DLR",
    "manages Kepler",
    "manages the project",
    "For more information on the asteroid initiative",
    "(NIMS) on the Galileo spacecraft imaged",
    "The Mariner 10 spacecraft was launched in",
#     "as part of a NASA-funded",
    "The AFM was developed by a",
    "Mars Science Laboratory project is using Curiosity",
    "Over the course of its mission,",
    "For information about NASA",
    "JPL is a division of",
    "STEREO, a two-year mission, launched",
    "Project will launch Curiosity",
    "Voyager 1 spacecraft launched",
    "For more information on the Flight Opportunities program",
    "The objective of SIR-A was to",
    "For more about Opportunity's mission",
    "For more information on the U.S.",
    "is a satellite mission designed to measure",
    "jointly funded MARSIS",
    "jointly funded the instrument",
    "For more about the Mars Exploration Program",
    "For more about NASA's Mars",
    "Images from the High Resolution Imaging Science Experiment and additional",
    "CRISM's mission:",
    "NASA's Voyager 2 spacecraft launched",
    "developed DAN in close cooperation with",
    "was captured by the mission's imaging camera",
#     "is being assembled and tested for launch",
    "For more information on the TOPEX",
#     "During a prime mission lasting nearly two years",
    "Mars Surveyor Operations Project operates",
    "The cooler was shipped to the",
    "The Mars Orbiter Camera can resolve",
    "as described by the Mars 2020 Science Definition Team",
    "purpose of Curiosity's MAHLI camera is",
    "was conceived, designed and built by",
    "The full image set for these observations can be seen",
    "As the first spacecraft ever to orbit Mercury",
    "images, multimedia and related materials",
    "Surrogate received support from",
    "WISE is an all-sky survey",
    "Mariner 4 was launched on",
    "which took this image",
    "This image taken by the hazard",
    "More information about the Kepler mission",
    "Opportunity completed its three-month",
    "Dawn is due to be captured",
    "ASTER is one of five Earth-observing instruments",
    "NASA's Jet Propulsion Laboratory manages",
    "For more information about NASA's Europa",
    "For more information on RapidScat",
    "RapidScat measures Earth's ocean surface wind speed",
    "More information about asteroids",
    "More information about the Deep Space Network",
    "NuSTAR's mission operations center",
    "For more information, visit",
    "WFIRST is managed at",
    "manage the mission",
    "More information about the NASA Great Observatories",
    "NED is hosted at",
#     "and links to data from other missions",
    "More information about ChemCam is available",
    "is managed by ESA",
    "spacecraft was built by",
    "spacecraft is managed by",
    "is funded by NASA",
    "For more information about ARIA, visit",
    "To see what the raw MOC image data look like",
#     "To learn more about",
    "About AIRS",
    "please visit our website",
#     "For additional information on",
#     "For additional information about",
    "The broad spectral coverage and high spectral resolution of ASTER",
    "is the project manager",
    "mission is part of NASA",
#     "For more information about",
    "on behalf of NASA",
    "management of the mission is by",
    "ended communications in November 2008",
    "manages the mission",
    "is a partnership between NASA",
    "For more information, see",
    "developed and managed by the",
    "The JPL UAVSAR team",
    "which is managed by the Jet Propulsion Laboratory",
    "GRACE is a collaborative endeavor",
    "manages the Curiosity project for NASA",
#     "a division of the California Institute of Technology",
    "a joint mission of the German, Italian, and United States space agencies",
    "More information on NEOWISE is online",
    "Additional information about the Hubble Space Telescope",
    "Agenzia Spaziale Italiana (ASI)",
    "AIRSAR is part of NASA's Earth Enterprise program",
    "and the instrument was built by Ball Aerospace and Technology Corp",
    "at Los Alamos National Laboratories",
    "at the Infrared Processing and Analysis Center",
    "at the Russian Aviation and Space Agency",
    "Background information and educational context for the images can be found at",
    "built and operates the orbiter's Context Camera",
    "built by Ball Aerospace Corporation",
    "built the orbiter and collaborates with JPL to operate it",
    "built the science instrument",
    "built under the leadership of the Max Planck Institute for Solar System Research",
    "Caltech manages JPL for NASA",
    "Cassini is a cooperative mission of NASA",
    "contributed mission-enabling technology",
    "contributions by the German Aerospace Center (DLR) Institute of Planetary Research",
    "CRISM is one of six science instruments on NASA's Mars Reconnaissance Orbiter",
    "data are analyzed by a joint U.S.-Italian science team",
    "data received from Galileo are posted on the World Wide Web",
    "Dawn is a project of the directorate's Discovery Program",
    "Dawn's mission is managed by JPL for NASA's Science Mission Directorate",
    "Dawn's mission is managed by NASA's Jet Propulsion Laboratory",
    "designed and built by Ball Aerospace & Technologies Corp",
    "Deutsche Agentur fuer Raumfahrtangelegenheiten",
    "developed and manages the Mars Pathfinder mission for NASA",
    "facility is part of the School of Earth and Space Exploration",
    "For a complete list of acknowledgements",
    "For a complete list of acknowledgments",
    "For additional images visit the Cassini imaging team homepage",
    "For images visit the Cassini imaging team home page",
    "For information regarding the use of images, see the MESSENGER image use policy",
    "For more about NASA's Curiosity mission",
    "For more information about CIBER,",
    "For more information about Curiosity",
    "For more information about DARPA Robotics Challenge",
    "For more information about EPOXI",
    "For more information about GRAIL",
    "For more information about Juno",
    "For more information about NASA's Mars Exploration Program",
    "For more information about robotics at JPL",
    "For more information about SMAP",
    "For more information about Spirit and Opportunity",
    "For more information about Spitzer",
    "For more information about Stardust-NExT",
    "For more information about the Cassini",
    "For more information about the Dawn mission, visit",
    "For more information about the Kepler",
    "For more information about the LDSD",
    "For more information about the visual and infrared mapping spectrometer",
    "For more information about the Voyager spacecraft, visit",
    "For more information about Voyager",
    "For more information on Aquarius",
    "For more information on Cassini",
    "For more information on NASA's ocean surface topography missions",
    "For more information on OCO-2",
    "For more information on UAVSAR",
    "for NASA's Office of Earth Science",
    "for NASA's Office of Space Science",
    "for NASA's Science Mission Directorate",
    "For publicly released image use, see ESA's Copyright Notice Images",
    "for the NASA Science Mission Directorate",
    "from the NASA Langley Research Center Atmospheric Science Data Center",
    "Herschel is a European Space Agency cornerstone mission",
    "HiRISE camera was built by Ball Aerospace and Technology",
    "HiRISE is one of six instruments on NASA's Mars Reconnaissance Orbiter",
    "HiRISE is operated by the University of Arizona, Tucson",
    "in collaboration with the Russian Aviation and Space Agency",
    "information about the Galaxy Evolution Explorer are online at",
    "information about the QuikScat mission and observations is available at",
#     "Infrared Processing and Analysis Center at the California Institute of Technology",
    "InSight is part of NASA's Discovery Program",
    "Institute of Computer and Communication Network Engineering, Braunschweig",
    "instrument was built by Ball Aerospace and Technology Corp",
    "Investigators at Arizona State University in Tempe",
    "is based at NASA's Jet Propulsion Laboratory",
    "is based at the Space Science Institute in Boulder",
    "is managed by NASA's Jet Propulsion Laboratory",
    "is managed for NASA's Office of Space Science and Applications by",
    "is operated by the University of Arizona, Tucson",
    "is part of NASA's Mission to Planet Earth",
    "is the prime contractor for the project",
    "Johnson Space Center, Houston, operate the science instruments",
    "JPL contributed mission-enabling technology",
    "JPL is a division of the California Institute of Technology",
    "JPL is an operating division of the California Institute of Technology",
    "JPL manages and controls the Voyager Project for NASA",
    "JPL manages the Mars Exploration Rover Project for NASA's Science Mission Directorate",
    "JPL manages the Voyager project for NASA",
    "JPL manages the Wide-field Infrared Survey Explorer",
    "JPL, a division of the California Institute of Technology",
    "Launch Services Program at the Kennedy Space Center",
    "led by Sapienza University of Rome",
    "Led by The Johns Hopkins University Applied Physics Laboratory",
    "Lockheed Martin Astronautics, Denver, is the prime contractor for",
    "Lockheed Martin Space Systems is the prime contractor for the project and built the spacecraft",
    "Lockheed Martin Space Systems, Denver, built",
    "Lockheed Martin Space Systems, Denver, is",
    "Malin Space Science Systems (MSSS) and the California Institute of Technology built",
    "Malin Space Science Systems and the California Institute of Technology built the",
#     "Malin Space Science Systems, San Diego",
    "managed by NASA's Marshall Space Flight Center in Huntsville, Alabama",
    "managed by the Goddard Space Flight Center",
    "managed by The Johns Hopkins University Applied Physics Laboratory",
    "managed for NASA by Jet Propulsion Laboratory",
    "managed for NASA by the California Institute of Technology",
    "manages Cassini for NASA's Office of Space Science",
    "manages the 2001 Mars Odyssey mission for NASA",
    "manages the Cassini mission for NASA's Office of Space Science",
    "manages the Deep Space Network for NASA Headquarters",
    "manages the Diviner instrument",
    "manages the Galileo mission for NASA's Office of Space Science",
    "manages the Lunar Reconnaissance Orbiter",
    "manages the Mars Reconnaissance Orbiter Project",
    "manages the Mars Science Laboratory mission",
    "manages the mission for NASA's Science Mission Directorate",
    "manages the Spitzer Space Telescope mission for NASA",
    "MISR was built and is managed by NASA's Jet Propulsion Laboratory",
    "Mission operations are conducted jointly from Lockheed Martin and from JPL",
    "mission's principal investigator, Edward Wright, is at UCLA",
    "More information about AIRS can be found at",
    "More information about ASTER is available at",
    "More information about Curiosity is at",
    "More information about Curiosity is online at",
    "More information about Dawn is online at",
    "More information about exoplanets and NASA's planet-finding program is at",
    "More information about Juno is online",
    "More information about NASA's role in the mission",
    "More information about Rosetta is available at",
    "More information about the Dawn mission is online at",
    "More information about the Deep Space Network is online at",
    "More information is online at",
    "MSSS operates the camera from its facilities in San Diego, CA",
    "NASA's Goddard Space Flight Center built and manages the mission for",
    "NASA's Jet Propulsion Laboratory manages the 2001 Mars Odyssey mission",
    "NASA's Jet Propulsion Laboratory, a division of Caltech in Pasadena, California",
    "NASA's Jet Propulsion Laboratory, a division of the California Institute of Technology",
    "NASA's Planck Project Office is based at JPL",
    "NASA's Quick Scatterometer (QuikScat) spacecraft",
    "NASA/JPL/MOLA",
    "NEAR was the first spacecraft launched in NASA's Discovery Program of",
    "New Horizons is part of the New Frontiers Program",
#     "on the European Space Agency's Mars Express orbiter",
    "on the Galileo mission home page at",
    "Operated by Arizona State University",
    "operated by Malin Space Science Systems",
    "operated by NASA Goddard Space Flight Center",
    "operated by the University of Arizona",
    "operated for NASA by the Association of Universities for Research in Astronomy",
    "operates the European Space Agency's Mars Express mission",
    "operations are conducted at the Spitzer Science Center",
    "operations are led by the University of Rome",
    "Orbital ATK, Inc., in Dulles, Virginia, designed and built the spacecraft",
    "Orbital Sciences Corporation of Dulles",
    "Other scientific partners include",
    "part of NASA's Mission to Planet Earth program",
#     "part of the Infrared Processing and Analysis Center at the California Institute of Technology",
    "Peter Smith is the Principal Investigator",
    "Philip Christensen at Arizona State  University",
    "Philip Christensen at Arizona State University",
    "Photojournal note:EarthKAM was formerly known as KidSat",
    "Planck is a European Space Agency mission, with significant participation from NASA",
    "QuikScat is managed for NASA's Science Mission Directorate",
    "Science operations and data processing will take place at",
    "science team is located at NASA's Jet Propulsion Laboratory, Pasadena, Calif",
    "SDO is managed by NASA's Goddard Space Flight Center",
    "see the MESSENGER image use policy",
    "See the NEAR web page at",
    "SIR-C was developed by NASA's Jet Propulsion Laboratory",
    "SIR-C/X-SAR, a joint mission of the German, Italian and United States space agencies",
    "sponsored by the Heliophysics Division of the Science Mission Directorate",
    "The Atlas V launch service is provided by United Launch Alliance",
    "The California Institute of Technology in Pasadena manages JPL for NASA",
    "The Cassini imaging team homepage",
    "The Cassini orbiter and its two onboard cameras were designed, developed and assembled at JPL",
    "The Cassini orbiter was designed, developed and assembled at JPL",
    "The Cassini-Huygens mission is a cooperative project of NASA",
    "the CRISM team includes expertise from",
    "The Dawn mission to Vesta and Ceres is managed by JPL",
    "The Dawn mission to Vesta and Ceres is managed by NASA",
    "the Deutsche Forschungsanstalt fuer Luft und Raumfahrt",
    "the European Space Agency and the Italian Space Agency",
    "The framing camera project is funded by NASA, the Max Planck Society and DLR",
    "The Framing Camera project is funded by the Max Planck Society",
    "The gamma ray spectrometer was provided by the University of Arizona",
    "The German Aerospace Center, the Max Planck Institute for Solar System Research, the Italian Space Agency and the Italian National Astrophysical Institute are international partners on the mission team",
    "the German space agency, Deutsche Agentur fuer Raumfahrtangelegenheiten (DARA)",
    "The High Resolution Imaging Science Experiment is operated by the University of Arizona",
    "The High Resolution Imaging Science Experiment is operated by",
    "The Hubble Space Telescope is a project of international cooperation",
    "The Imager for Mars Pathfinder (IMP) was developed by",
    "was developed, built and tested by",
    "The imaging operations center is based at the Space Science Institute",
    "The InSight Project is managed by NASA's Jet Propulsion Laboratory",
    "the Italian space agency, Agenzia Spaziale Italiana (ASI)",
    "The Jet Propulsion Laboratory operates the Mars Global Surveyor spacecraft",
    "The Jet Propulsion Laboratory, a division of the California Institute of Technology in Pasadena",
    "The Jet Propulsion Laboratory, Pasadena, CA manages the mission for NASA's Office of Space Science",
    "The Jet Propulsion Laboratory's Mars Surveyor Operations Project",
    "The Johns Hopkins University Applied Physics Laboratory in Laurel, Maryland",
    "The Low-Density Supersonic Decelerator Project is managed by JPL",
    "The Lunar Reconnaissance Orbiter Camera was designed to acquire data for landing site certification",
    "The magnetometer team homepage is",
    "the major partner in science, operations and data processing of X-SAR",
    "The Mariner 10 mission, managed by the Jet Propulsion Laboratory",
    "The MISR data were obtained from the NASA Langley",
    "The mission was competitively selected under NASA's",
    "The NASA Herschel Science Center, part of the Infrared Processing and Analysis Center at Caltech",
    "The National Oceanic and Atmospheric Administration has contributed",
    "The Southwest Research Institute, based in San Antonio, leads",
    "The Space Telescope Science Institute (STScI) in Baltimore conducts Hubble science operations",
    "The Terra mission is part of NASA's Science Mission Directorate",
    "NASA's Space Technology Mission Directorate funds the LDSD mission",
    "manages Kepler's ground system development",
    "Juno aims to understand the origin",
    "STEREO, a two-year mission, launched",
    "The Terra satellite is managed by",
    "The Terra spacecraft is managed by",
    "The THEMIS investigation is led by Dr",
    "The Thermal Emission Imaging System (THEMIS) was developed by Arizona State University",
    "The ultraviolet imaging spectrograph team home page",
    "The University of Arizona, Tucson, operates",
    "The University of California, Los Angeles, is responsible for",
    "The visual and infrared mapping spectrometer team homepage",
    "The Voyager Mission is conducted by JPL for NASA's Office of Space Science and Applications",
    "The Voyager project is managed for NASA by the Jet Propulsion Laboratory",
    "These images are from MESSENGER, a NASA Discovery mission",
    "This array of indirect evidence of past life will be reported in the Aug",
    "This image and other images and data received from Galileo are posted",
    "This image and other images and data received from the Hubble Space Telescope are posted on the World Wide Web",
    "This mission will land Curiosity on Mars",
    "This research was carried out at JPL",
    "To see images of KidSat",
    "Topex/Poseidon mission is managed by",
    "TOPEX/Poseidon project web page at",
    "UCLA is home institution of Diviner's principal investigator, David Paige",
    "UCLA is responsible for overall Dawn mission science",
    "under contract to JPL",
    "under the leadership of the Max Planck Institute for Solar System Research",
    "visual and infrared mapping spectrometer team homepage is at",
    "visual and infrared mapping spectrometer team homepage",
    "was built by Ball Aerospace & Technologies Corp",
    "was built by the Lockheed Martin Solar Astrophysics Laboratory",
    "was built by the Space Dynamics Laboratory",
    "was developed by the Dornier and Alenia Spazio companies",
    "was developed by the University of Arizona Lunar and Planetary Laboratory",
    "was launched from Vandenberg Air Force Base",
    "was provided by Arizona State University",
    "was provided by the Italian Space Agency",
    "was provided by the University of Arizona",
    "were retrieved from the Planetary Data System's Cassini archives",
    "which provided the high-energy neutron detector",
    "which provided the neutron spectrometer",
    "which was built by Ball Aerospace & Technologies Corp",
    "which was designed and built by JPL",
    "with its industrial partner, Lockheed Martin Astronautics",
    "with science instruments provided by consortia of European institutes",
]
