################################################################################
# dicts/HOST_INFO.py
#
# Usage:
#   from HOST_INFO import HOST_INFO
#
# HOST_INFO is a dictionary that translates the lower-case name or abbreviation
# of a host into a tuple containing the full name of the host, mission name, and
# host type (e.g., "Orbiter" or "Probe").
################################################################################

HOST_INFO = {
    '2001 mars odyssey'                 : ('Mars Odyssey', '2001 Mars Odyssey', 'Orbiter'),
    'arecibo observatory'               : ('Arecibo Observatory', 'National Astronomy and Ionosphere Center (NAIC)', 'Ground-Based Observatory'),
    'arecibo'                           : ('Arecibo Observatory', 'National Astronomy and Ionosphere Center (NAIC)', 'Ground-Based Observatory'),
    'beagle 2'                          : ('Beagle 2', 'Mars Express (MEX)', 'Lander'),
    'cassini orbiter'                   : ('Cassini Orbiter', 'Cassini-Huygens', 'Orbiter'),
    'clementine 1'                      : ('Clementine', 'Deep Space Program Science Experiment (DSPSE)', 'Orbiter'),
    'clementine'                        : ('Clementine', 'Deep Space Program Science Experiment (DSPSE)', 'Orbiter'),
    'curiosity rover'                   : ('Curiosity Rover', 'Mars Science Laboratory (MSL)', 'Rover'),
    'curiosity'                         : ('Curiosity Rover', 'Mars Science Laboratory (MSL)', 'Rover'),
    'dart'                              : ('DART', 'Double Asteroid Redirect Test (DART)', 'Impactor'),
    'davinci orbiter'                   : ('DAVINCI+ Orbiter', 'DAVINCI+', 'Orbiter'),
    'davinci probe'                     : ('DAVINCI+ Probe', 'DAVINCI+', 'Probe'),
    'davinci'                           : ('DAVINCI+ Probe', 'DAVINCI+', 'Probe'),
    'davinci+ orbiter'                  : ('DAVINCI+ Orbiter', 'DAVINCI+', 'Orbiter'),
    'davinci+ probe'                    : ('DAVINCI+ Probe', 'DAVINCI+', 'Probe'),
    'davinci+'                          : ('DAVINCI+ Probe', 'DAVINCI+', 'Probe'),
    'dawn'                              : ('Dawn', 'Dawn', 'Orbiter'),
    'deep impact  (dixi)'               : ('Deep Impact', 'Deep Impact', 'Impactor'),
    'deep impact (dixi)'                : ('Deep Impact', 'Deep Impact', 'Impactor'),
    'deep impact'                       : ('Deep Impact', 'Deep Impact', 'Impactor'),
    'deep space 1 '                     : ('Deep Space 1', 'Deep Space 1 (DS1)', 'Flyby Spacecraft'),
    'deep space 1 (ds1)'                : ('Deep Space 1', 'Deep Space 1 (DS1)', 'Flyby Spacecraft'),
    'deep space program science experiment (dspse)': ('Clementine', 'Deep Space Program Science Experiment (DSPSE)', 'Orbiter'),
    'deep space program science experiment': ('Clementine', 'Deep Space Program Science Experiment (DSPSE)', 'Orbiter'),
    'double asteroid redirect test (dart)': ('DART', 'Double Asteroid Redirect Test (DART)', 'Impactor'),
    'double asteroid redirect test'     : ('DART', 'Double Asteroid Redirect Test (DART)', 'Impactor'),
    'dragonfly'                         : ('Dragonfly', 'Dragonfly', 'Helicopter'),
    'ds1'                               : ('Deep Space 1', 'Deep Space 1 (DS1)', 'Flyby Spacecraft'),
    'dspse'                             : ('Clementine', 'Deep Space Program Science Experiment (DSPSE)', 'Orbiter'),
    'europa clipper'                    : ('Europa Clipper', 'Europa Clipper', 'Orbiter'),
    'galileo orbiter'                   : ('Galileo Orbiter', 'Galileo', 'Orbiter'),
    'galileo probe'                     : ('Galileo Probe','Galileo', 'Probe'),
    'galileo'                           : ('Galileo Orbiter', 'Galileo', 'Orbiter'),
    'gdscc'                             : ('Goldstone Deep Space Communications Complex (GDSCC)', 'Deep Space Network (DSN)', 'Ground-Based Observatory'),
    'cdscc'                             : ('Canberra Deep Space Communications Complex (CDSCC)', 'Deep Space Network (DSN)', 'Ground-Based Observatory'),
    'gemini north telescope'            : ('Gemini North Telescope', 'Gemini North Telescope', 'Ground-Based Telescope'),
    'gemini north'                      : ('Gemini North Telescope', 'Gemini North Telescope', 'Ground-Based Telescope'),
    'herschel'                          : ('Herschel Space Observatory', 'Herschel Space Observatory', 'Space Telescope'),
    'herschel space observatory'        : ('Herschel Space Observatory', 'Herschel Space Observatory', 'Space Telescope'),
    'hst'                               : ('Hubble Space Telescope', 'Hubble Space Telescope (HST)', 'Space Telescope'),
    'hubble space telescope (hst)'      : ('Hubble Space Telescope', 'Hubble Space Telescope (HST)', 'Space Telescope'),
    'huygens probe'                     : ('Huygens Probe', 'Cassini-Huygens', 'Probe'),
    'huygens'                           : ('Huygens Probe', 'Cassini-Huygens', 'Probe'),
    'infrared telescope facility (irtf)': ('Infrared Telescope Facility', 'Infrared Telescope Facility (IRTF)', 'Ground-Based Telescope'),
    'infrared telescope facility'       : ('Infrared Telescope Facility', 'Infrared Telescope Facility (IRTF)', 'Ground-Based Telescope'),
    'ingenuity'                         : ('Ingenuity', 'Mars 2020', 'Helicopter'),
    'insight lander'                    : ('InSight Lander', 'InSight', 'Lander'),
    'insight mars lander'               : ('InSight Lander', 'InSight', 'Lander'),
    'insight'                           : ('InSight Lander', 'InSight', 'Lander'),
    'irtf'                              : ('Infrared Telescope Facility', 'Infrared Telescope Facility (IRTF)', 'Ground-Based Telescope'),
    'james webb space telescope (jwst)' : ('James Webb Space Telescope', 'James Webb Space Telescope (JWST)', 'Space Telescope'),
    'james webb space telescope'        : ('James Webb Space Telescope', 'James Webb Space Telescope (JWST)', 'Space Telescope'),
    'juice'                             : ('Jupiter Icy Moons Explorer', 'Jupiter Icy Moons Explorer (JUICE)', 'Orbiter'),
    'jwst'                              : ('James Webb Space Telescope', 'James Webb Space Telescope (JWST)', 'Space Telescope'),
    'keck 1 telescope'                  : ('Keck 1 Telescope', 'W. M. Keck Observatory', 'Ground-Based Telescope'),
    'keck 1'                            : ('Keck 1 Telescope', 'W. M. Keck Observatory', 'Ground-Based Telescope'),
    'keck 2 telescope'                  : ('Keck 2 Telescope', 'W. M. Keck Observatory', 'Ground-Based Telescope'),
    'keck 2'                            : ('Keck 2 Telescope', 'W. M. Keck Observatory', 'Ground-Based Telescope'),
    'keck observatory'                  : ('Keck Telescope', 'W. M. Keck Observatory', 'Ground-Based Telescope'),
    'keck telescope'                    : ('Keck Telescope', 'W. M. Keck Observatory', 'Ground-Based Telescope'),
    'keck'                              : ('Keck Telescope', 'W. M. Keck Observatory', 'Ground-Based Telescope'),
    'kepler spacecraft'                 : ('Kepler', 'Kepler', 'Space Telescope'),
    'kepler'                            : ('Kepler', 'Kepler', 'Space Telescope'),
    'la sagra observatory'              : ('La Sagra Observatory', 'Astronomical Observatory of Mallorca', 'Ground-Based Telescope'),
    'lcross'                            : ('Lunar Crater Observation and Sensing Satellite', 'Lunar Crater Observation and Sensing Satellite (LCROSS)', 'Impactor'),
    'lro'                               : ('Lunar Reconnaissance Orbiter', 'Lunar Reconnaissance Orbiter (LRO)', 'Orbiter'),
    'lunar crater observation and sensing satellite (lcross)': ('Lunar Crater Observation and Sensing Satellite', 'Lunar Crater Observation and Sensing Satellite (LCROSS)', 'Impactor'),
    'lunar crater observation and sensing satellite': ('Lunar Crater Observation and Sensing Satellite', 'Lunar Crater Observation and Sensing Satellite (LCROSS)', 'Impactor'),
    'lunar reconnaissance orbiter (lro)': ('Lunar Reconnaissance Orbiter', 'Lunar Reconnaissance Orbiter (LRO)', 'Orbiter'),
    'lunar reconnaissance orbiter'      : ('Lunar Reconnaissance Orbiter', 'Lunar Reconnaissance Orbiter (LRO)', 'Orbiter'),
    'magellan'                          : ('Magellan', 'Magellan', 'Orbiter'),
    'marco-a'                           : ('MarCO-A', 'Mars Cube One (MarCO)', 'Flyby Spacecraft'),
    'marco-b'                           : ('MarCO-B', 'Mars Cube One (MarCO)', 'Flyby Spacecraft'),
    'marco'                             : ('MarCO-B', 'Mars Cube One (MarCO)', 'Flyby Spacecraft'),
    'mariner 1'                         : ('Mariner 1', 'Mariner', 'Flyby Spacecraft'),
    'mariner 10'                        : ('Mariner 10', 'Mariner', 'Flyby Spacecraft'),
    'mariner 10'                        : ('Mariner 10', 'Mariner', 'Flyby Spacecraft'),
    'mariner 2'                         : ('Mariner 2', 'Mariner', 'Flyby Spacecraft'),
    'mariner 3'                         : ('Mariner 3', 'Mariner', 'Flyby Spacecraft'),
    'mariner 4'                         : ('Mariner 4', 'Mariner', 'Flyby Spacecraft'),
    'mariner 5'                         : ('Mariner 5', 'Mariner', 'Flyby Spacecraft'),
    'mariner 6'                         : ('Mariner 6', 'Mariner', 'Flyby Spacecraft'),
    'mariner 7'                         : ('Mariner 7', 'Mariner', 'Flyby Spacecraft'),
    'mariner 8'                         : ('Mariner 8', 'Mariner', 'Flyby Spacecraft'),
    'mariner 9'                         : ('Mariner 9', 'Mariner', 'Flyby Spacecraft'),
    'mariner mars 1964 (mariner 4)'     : ('Mariner 4', 'Mariner', 'Flyby Spacecraft'),
    'mariner mars 1964'                 : ('Mariner 4', 'Mariner', 'Flyby Spacecraft'),
    'mariner mars 1969 (mariner 7)'     : ('Mariner 7', 'Mariner', 'Flyby Spacecraft'),
    'mariner mars 1969'                 : ('Mariner 7', 'Mariner', 'Flyby Spacecraft'),
    'mariner mars 1971 (mariner 9)'     : ('Mariner 9', 'Mariner', 'Flyby Spacecraft'),
    'mariner mars 1971'                 : ('Mariner 9', 'Mariner', 'Flyby Spacecraft'),
    'mariner venus mercury (mariner 10)': ('Mariner 9', 'Mariner', 'Flyby Spacecraft'),
    'mariner venus mercury'             : ('Mariner 10', 'Mariner', 'Flyby Spacecraft'),
    'mars 2020 rover'                   : ('Perseverance', 'Mars 2020', 'Rover'),
    'mars 2020'                         : ('Perseverance', 'Mars 2020', 'Rover'),
    'mars atmosphere and volatile evolution (maven)': ('MAVEN', 'Mars Atmosphere and Volatile Evolution (MAVEN)', 'Orbiter'),
    'mars atmosphere and volatile evolution (maven)': ('MAVEN', 'Mars Atmosphere and Volatile Evolution (MAVEN)', 'Orbiter'),
    'mars atmosphere and volatile evolution mission (maven)': ('MAVEN', 'Mars Atmosphere and Volatile Evolution (MAVEN)', 'Orbiter'),
    'mars atmosphere and volatile evolution': ('MAVEN', 'Mars Atmosphere and Volatile Evolution (MAVEN)', 'Orbiter'),
    'mars climate orbiter (mco)'        : ('Mars Climate Orbiter', 'Mars Climate Orbiter (MCO)', 'Orbiter'),
    'mars climate orbiter'              : ('Mars Climate Orbiter', 'Mars Climate Orbiter (MCO)', 'Orbiter'),
    'mars exploration rover (mer)'      : ('Mars Exploration Rover', 'Mars Exploration Rover (MER)', 'Rover'),
    'mars exploration rover'            : ('Mars Exploration Rover', 'Mars Exploration Rover (MER)', 'Rover'),
    'mars express (mex) lander'         : ('Beagle 2', 'Mars Express (MEX)', 'Lander'),
    'mars express (mex) orbiter'        : ('Mars Express Orbiter', 'Mars Express (MEX)', 'Orbiter'),
    'mars express (mex)'                : ('Mars Express Orbiter', 'Mars Express (MEX)', 'Orbiter'),
    'mars express lander'               : ('Beagle 2', 'Mars Express (MEX)', 'Lander'),
    'mars express orbiter'              : ('Mars Express Orbiter', 'Mars Express (MEX)', 'Orbiter'),
    'mars express'                      : ('Mars Express Orbiter', 'Mars Express (MEX)', 'Orbiter'),
    'mars global surveyor (mgs)'        : ('Mars Global Surveyor', 'Mars Global Surveyor (MGS)', 'Orbiter'),
    'mars global surveyor orbiter (mgs)': ('Mars Global Surveyor', 'Mars Global Surveyor (MGS)', 'Orbiter'),
    'mars global surveyor orbiter'      : ('Mars Global Surveyor', 'Mars Global Surveyor (MGS)', 'Orbiter'),
    'mars global surveyor'              : ('Mars Global Surveyor', 'Mars Global Surveyor (MGS)', 'Orbiter'),
    'mars helicopter'                   : ('Ingenuity', 'Mars 2020', 'Helicopter'),
    'mars insight lander'               : ('InSight Lander', 'InSight', 'Lander'),
    'mars insight'                      : ('InSight Lander', 'InSight', 'Lander'),
    'mars odyssey'                      : ('Mars Odyssey', '2001 Mars Odyssey', 'Orbiter'),
    'mars pathfinder (mpf) lander'      : ('Mars Pathfinder Lander', 'Mars Pathfinder (MPF)', 'Lander'),
    'mars pathfinder (mpf) rover'       : ('Sojourner', 'Mars Pathfinder (MPF)', 'Rover'),
    'mars pathfinder (mpf)'             : ('Mars Pathfinder Lander', 'Mars Pathfinder (MPF)', 'Lander'),
    'mars pathfinder lander'            : ('Mars Pathfinder Lander', 'Mars Pathfinder (MPF)', 'Lander'),
    'mars pathfinder rover'             : ('Sojourner', 'Mars Pathfinder (MPF)', 'Rover'),
    'mars pathfinder'                   : ('Mars Pathfinder Lander', 'Mars Pathfinder (MPF)', 'Lander'),
    'mars reconnaissance orbiter (mro)' : ('Mars Reconnaissance Orbiter', 'Mars Reconnaissance Orbiter (MRO)', 'Orbiter'),
    'mars reconnaissance orbiter'       : ('Mars Reconnaissance Orbiter', 'Mars Reconnaissance Orbiter (MRO)', 'Orbiter'),
    'mars sample return (msr)'          : ('Mars Sample Return', 'Mars Sample Return (MSR)', 'Rover'),
    'mars sample return'                : ('Mars Sample Return', 'Mars Sample Return (MSR)', 'Rover'),
    'mars science laboratory (msl)'     : ('Curiosity Rover', 'Mars Science Laboratory (MSL)', 'Rover'),
    'mars science laboratory'           : ('Curiosity Rover', 'Mars Science Laboratory (MSL)', 'Rover'),
    'mars volcanic emission life scout (marvel)': ('MARVEL', 'Mars Volcanic Emission Life Scout (MARVEL)', 'Orbiter'),
    'mars volcanic emission life scout' : ('MARVEL', 'Mars Volcanic Emission Life Scout (MARVEL)', 'Orbiter'),
    'marvel'                            : ('MARVEL', 'Mars Volcanic Emission Life Scout (MARVEL)', 'Orbiter'),
    'maven'                             : ('MAVEN', 'Mars Atmosphere and Volatile Evolution (MAVEN)', 'Orbiter'),
    'mco'                               : ('Mars Climate Orbiter (MCO)', 'Mars Climate Orbiter (MCO)', 'Orbiter'),
    'mdscc'                             : ('Madrid Deep Space Communications Complex (MDSCC)', 'Deep Space Network (DSN)', 'Ground-Based Observatory'),
    'mer-a'                             : ('Spirit (MER-A)', 'Mars Exploration Rover (MER)', 'Rover'),
    'mer-b'                             : ('Opportunity (MER-B)', 'Mars Exploration Rover (MER)', 'Rover'),
    'mer'                               : ('Mars Exploration Rover (MER)', 'Mars Exploration Rover (MER)', 'Rover'),
    'mer'                               : ('Mars Exploration Rover (MER)', 'Mars Exploration Rover (MER)', 'Rover'),
    'messenger'                         : ('MESSENGER', 'MESSENGER', 'Orbiter'),
    'mex'                               : ('Mars Express Orbiter', 'Mars Express (MEX)', 'Orbiter'),
    'mgs'                               : ('Mars Global Surveyor', 'Mars Global Surveyor (MGS)', 'Orbiter'),
    'mpf'                               : ('Mars Pathfinder Lander', 'Mars Pathfinder (MPF)', 'Lander'),
    'mro'                               : ('Mars Reconnaissance Orbiter', 'Mars Reconnaissance Orbiter (MRO)', 'Orbiter'),
    'msl'                               : ('Curiosity Rover', 'Mars Science Laboratory (MSL)', 'Rover'),
    'msr'                               : ('Mars Sample Return', 'Mars Sample Return (MSR)', 'Rover'),
    'near earth asteroid rendezvous'    : ('NEAR Shoemaker', 'NEAR Shoemaker', 'Orbiter'),
    'near shoemaker'                    : ('NEAR Shoemaker', 'NEAR Shoemaker', 'Orbiter'),
    'near-earth object camera (neocam)' : ('Near-Earth Object Camera', 'Near-Earth Object Camera (NEOCam)', 'Space Telescope'),
    'near-earth object camera'          : ('Near-Earth Object Camera', 'Near-Earth Object Camera (NEOCam)', 'Space Telescope'),
    'near'                              : ('NEAR Shoemaker', 'NEAR Shoemaker', 'Orbiter'),
    'neocam'                            : ('NEOCam', 'Near-Earth Object Camera (NEOCam)', 'Space Telescope'),
    'neowise'                           : ('NEOWISE', 'Near-Earth Object Wide-field Infrared Survey Explorer (NEOWISE)', 'Space Telescope'),
    'neowise telescope'                 : ('NEOWISE', 'Near-Earth Object Wide-field Infrared Survey Explorer (NEOWISE)', 'Space Telescope'),
    'opportunity (mer-b)'               : ('Opportunity (MER-B)', 'Mars Exploration Rover (MER)', 'Rover'),
    'opportunity'                       : ('Opportunity (MER-B)', 'Mars Exploration Rover (MER)', 'Rover'),
    'palomar'                           : ('Palomar Observatory', 'Palomar Observatory', 'Ground-Based Telescope'),
    'palomar observatory'               : ('Palomar Observatory', 'Palomar Observatory', 'Ground-Based Telescope'),
    'perseverance'                      : ('Perseverance', 'Mars 2020', 'Rover'),
    'philae lander'                     : ('Philae Lander', 'Rosetta', 'Lander'),
    'philae'                            : ('Philae Lander', 'Rosetta', 'Lander'),
    'phoenix lander'                    : ('Phoenix Lander', 'Phoenix', 'Lander'),
    'phoenix mars lander'               : ('Phoenix Lander', 'Phoenix', 'Lander'),
    'phoenix'                           : ('Phoenix Lander', 'Phoenix', 'Lander'),
    'pioneer 10'                        : ('Pioneer 10', 'Pioneer', 'Flyby Spacecraft'),
    'pioneer 11'                        : ('Pioneer 11', 'Pioneer', 'Flyby Spacecraft'),
    'pioneer 12'                        : ('Pioneer Venus Orbiter', 'Pioneer Venus', 'Orbiter'),
    'pioneer 6'                         : ('Pioneer 6' , 'Pioneer', 'Flyby Spacecraft'),
    'pioneer 7'                         : ('Pioneer 7' , 'Pioneer', 'Flyby Spacecraft'),
    'pioneer 8'                         : ('Pioneer 8' , 'Pioneer', 'Flyby Spacecraft'),
    'pioneer 9'                         : ('Pioneer 9' , 'Pioneer', 'Flyby Spacecraft'),
    'pioneer venus orbiter'             : ('Pioneer Venus Orbiter', 'Pioneer Venus', 'Orbiter'),
    'pioneer venus'                     : ('Pioneer Venus Orbiter', 'Pioneer Venus', 'Orbiter'),
    'psyche'                            : ('Psyche', 'Psyche', 'Orbiter'),
    'rosetta orbiter'                   : ('Rosetta Orbiter', 'Rosetta', 'Orbiter'),
    'rosetta'                           : ('Rosetta Orbiter', 'Rosetta', 'Orbiter'),
    'siding spring observatory'         : ('Siding Spring Observatory', 'Siding Spring Observatory', 'Ground-Based Telescope'),
    'sojourner'                         : ('Sojourner', 'Mars Pathfinder (MPF)', 'Rover'),
    'spirit (mer-a)'                    : ('Spirit (MER-A)', 'Mars Exploration Rover (MER)', 'Rover'),
    'spirit'                            : ('Spirit (MER-A)', 'Mars Exploration Rover (MER)', 'Rover'),
    'spitzer space telescope'           : ('Spitzer Space Telescope', 'Spitzer Space Telescope', 'Space Telescope'),
    'spitzer telescope'                 : ('Spitzer Space Telescope', 'Spitzer Space Telescope', 'Space Telescope'),
    'spitzer'                           : ('Spitzer Space Telescope', 'Spitzer Space Telescope', 'Space Telescope'),
    'stardust'                          : ('Stardust', 'Stardust', 'Sample Return'),
    'stardustnext'                      : ('Stardust', 'Stardust', 'Sample Return'),
    'subaru telescope'                  : ('Subaru Telescope', 'Subaru Telescope', 'Ground-Based Telescope'),
    'subaru'                            : ('Subaru Telescope', 'Subaru Telescope', 'Ground-Based Telescope'),
    'surveyor 1'                        : ('Surveyor 1', 'Surveyor', 'Lander'),
    'surveyor 2'                        : ('Surveyor 2', 'Surveyor', 'Lander'),
    'surveyor 3'                        : ('Surveyor 3', 'Surveyor', 'Lander'),
    'surveyor 4'                        : ('Surveyor 4', 'Surveyor', 'Lander'),
    'surveyor 5'                        : ('Surveyor 5', 'Surveyor', 'Lander'),
    'surveyor 6'                        : ('Surveyor 6', 'Surveyor', 'Lander'),
    'surveyor 7'                        : ('Surveyor 7', 'Surveyor', 'Lander'),
    'transiting planets and planetesimals small telescope (trappist)': ('TRAPPIST', 'Transiting Planets and Planetesimals Small Telescope (TRAPPIST)', 'Ground-Based Telescope'),
    'transiting planets and planetesimals small telescope': ('TRAPPIST', 'Transiting Planets and Planetesimals Small Telescope (TRAPPIST)', 'Ground-Based Telescope'),
    'trappist'                          : ('TRAPPIST', 'Transiting Planets and Planetesimals Small Telescope (TRAPPIST)', 'Ground-Based Telescope'),
    'venus express'                     : ('Venus Express', 'Venus Express (VEX)', 'Orbiter'),
    'veritas'                           : ('VERITAS', 'VERITAS', 'Orbiter'),
    'vex'                               : ('Venus Express', 'Venus Express (VEX)', 'Orbiter'),
    'viking 1 lander'                   : ('Viking 1 Lander', 'Viking', 'Lander'),
    'viking 1 orbiter'                  : ('Viking 1 Orbiter', 'Viking', 'Orbiter'),
    'viking 2 lander'                   : ('Viking 2 Lander', 'Viking', 'Lander'),
    'viking 2 orbiter'                  : ('Viking 2 Orbiter', 'Viking', 'Orbiter'),
    'viking lander 1'                   : ('Viking 1 Lander', 'Viking', 'Lander'),
    'viking lander 2'                   : ('Viking 2 Lander', 'Viking', 'Lander'),
    'viking lander'                     : ('Viking Lander', 'Viking', 'Lander'),
    'viking orbiter 1'                  : ('Viking 1 Orbiter', 'Viking', 'Orbiter'),
    'viking orbiter 2'                  : ('Viking 2 Orbiter', 'Viking', 'Orbiter'),
    'viking orbiter'                    : ('Viking Orbiter', 'Viking', 'Orbiter'),
    'voyager 1'                         : ('Voyager 1', 'Voyager', 'Flyby Spacecraft'),
    'voyager 2'                         : ('Voyager 2', 'Voyager', 'Flyby Spacecraft'),
    'w. m. keck observatory'            : ('Keck Telescope', 'W. M. Keck Observatory', 'Ground-Based Telescope'),
    "nasa's mars pathfinder lander"     : ('Mars Pathfinder Lander', 'Mars Pathfinder (MPF)', 'Lander'),
    'wfirst'                            : ('WFIRST', 'Wide-Field Infrared Survey Telescope (WFIRST)', 'Space Telescope'),

}

################################################################################
