################################################################################
# dicts/HOST_FROM_INSTRUMENT.py
#
# Usage:
#   from HOST_FROM_INSTRUMENT import HOST_FROM_INSTRUMENT
#
# HOST_FROM_INSTRUMENT is a dictionary that translates the lower-case name or
# abbreviation of an instrument into the full name of the instrument host.
################################################################################

HOST_FROM_INSTRUMENT = {
    'acrim 3'   : 'Active Cavity Irradiance Monitor Satellite (AcrimSat)',
    'acs'       : 'Hubble Space Telescope',
    'alma'      : 'Atacama Large Millimeter/submillimeter Array (ALMA)',
    'asi/met'   : 'Mars Pathfinder Lander',
    'aster'     : 'Terra',
    'apxs'      : 'Curiosity Rover',
    'cda'       : 'Cassini Orbiter',
    'cida'      : 'Stardust',
    'cfht'      : 'Canada-France-Hawaii Telescope (CFHT)',
    'chemcam'   : 'Curiosity Rover',
    'chemin'    : 'Curiosity Rover',
    'chimra'    : 'Curiosity Rover',
    'cirs'      : 'Cassini Orbiter',
    'civa'      : 'Philae Lander',
    'crism'     : 'Mars Reconnaissance Orbiter',
    'ctx'       : 'Mars Reconnaissance Orbiter',
    'dan'       : 'Dynamic Albedo of Neutrons (DAN)',
    'dse'       : 'Stardust',
    'dfmi'      : 'Stardust',
    'disr'      : 'Huygens Probe',
    'dsoc'      : 'Psyche',
    'e-themis'  : 'Europa Clipper',
    'eis'       : 'Europa Clipper',
    'europa-uvs': 'Europa Clipper',
    'foc'       : 'Hubble Space Telescope',
    'goldstone solar system radar': 'Goldstone Deep Space Communications Complex (GDSCC)',
    'grns'      : ['MESSENGER', 'Psyche'],
    'grs'       : 'Mars Odyssey',
    'hazcam'    : ['Spirit (MER-A)', 'Opportunity (MER-B)', 'Curiosity Rover'],
    'hifi'      : 'Herschel Space Observatory',
    'hirise'    : 'Mars Reconnaissance Orbiter',
    'hri'       : 'Deep Impact',
    'hrsc'      : 'Mars Express',
    'icemag'    : 'Europa Clipper',
    'icc'       : 'InSight',
    'imp'       : 'Mars Pathfinder Lander',
    'irac'      : 'Spitzer Space Telescope',
    'irs'       : 'Spitzer Space Telescope',
    'iss'       : ['Voyager 1', 'Voyager 2', 'Cassini Orbiter'],
    'irtf'      : 'Infrared Telescope Facility',
    'inms'      : 'Cassini Orbiter',
    'jiram'     : 'Juno',
    'junocam'   : 'Juno',
    "l'mvic"    : 'Lucy',
    "l'lorri"   : 'Lucy',
    "l'tes"     : 'Lucy',
    'leisa'     : 'New Horizons',
    'lorri'     : 'New Horizons',
    'mahli'     : ['Curiosity Rover', 'Perseverance'],
    'marci'     : 'Mars Reconnaissance Orbiter',
    'marie'     : 'Mars Odyssey',
    'marsis'    : 'Mars Express',
    'marvel'    : 'Mars Scout',
    'mascs'     : 'MESSENGER',
    'maspex'    : 'Europa Clipper',
    'mastcam'   : 'Curiosity Rover',
    'mdis'      : 'MESSENGER',
    'meca'      : 'Phoenix Mars Lander',
    'met'       : 'Phoenix Mars Lander',
    'mb'        : ['Spirit (MER-A)', 'Opportunity (MER-B)'],
    'mi'        : ['Spirit (MER-A)', 'Opportunity (MER-B)'],
    'mini-tes'  : ['Spirit (MER-A)', 'Opportunity (MER-B)'],
    'miro'      : 'Rosetta Orbiter',
    'mise'      : 'Europa Clipper',
    'misr'      : 'Terra',
    'mla'       : 'MESSENGER',
    'moc'       : 'Mars Global Surveyor',
    'mri'       : 'Deep Impact',
    'mola'      : 'Mars Global Surveyor',
    'moxie'     : 'Perseverance',
    'msi'       : ['NEAR Shoemaker', 'Psyche'],
    'mvic'      : 'New Horizons',
    'navcam'    : ['Curiosity Rover', 'Rosetta Orbiter'],
    'nc'        : 'Stardust',
    'ngims'     : 'MAVEN',
    'nicmos'    : 'Hubble Space Telescope',
    'nims'      : 'Galileo Orbiter',
    'nis'       : 'NEAR Shoemaker',
    'nlr'       : 'NEAR Shoemaker',
    'omega'     : 'Mars Express',
    'osiris'    : 'Rosetta Orbiter',
#     'pancam'    : ['Spirit (MER-A)', 'Opportunity (MER-B)'],
    'pims'      : 'Europa Clipper',
    'pps'       : ['Voyager 1', 'Voyager 2'],
    'rad'       : 'Curiosity Rover',
    'ralph'     : 'New Horizons',
    'reason'    : 'Europa Clipper',
    'rems'      : 'Curiosity Rover',
    'rex'       : 'New Horizons',
    'rime'      : 'Jupiter Icy Moons Explorer',
    'rolis'     : 'Philae Lander',
    'rss'       : ['Voyager 1', 'Voyager 2', 'Cassini Orbiter'],
    'sam'       : 'Curiosity Rover',
    'sharad'    : 'Mars Reconnaissance Orbiter',
    'ssc'       : 'Stardust',
    'suda'      : 'Europa Clipper',
    'swap'      : 'New Horizons',
    'tega'      : 'Phoenix Mars Lander',
    'tes'       : 'Mars Global Surveyor',
    'themis'    : ['Mars Odyssey', 'Perseverance'],
    'trappist'  : 'TRAPPIST',
#     'uvis'      : 'Cassini Orbiter',
    'uvs'       : ['Voyager 1', 'Voyager 2'],
    'val'       : 'DAVINCI+',
    'vasi'      : 'DAVINCI+',
    'vem'       : 'VERITAS',
    'vendi'     : 'DAVINCI+',
    'vims'      : 'Cassini Orbiter',
    'virtis'    : ['Rosetta Orbiter', 'Venus Express'],
    'visar'     : 'VERITAS',
    'vms'       : 'DAVINCI+',
    'vlts'      : 'DAVINCI+',
    'wfc3'      : 'Hubble Space Telescope',
    'wfpc2'     : 'Hubble Space Telescope',
    'xrs'       : 'MESSENGER',

    'alice ultraviolet spectrometer': 'New Horizons',
    'arecibo observatory'           : 'Arecibo Observatory',
    'arecibo radar data'            : 'Arecibo Observatory',
    'arecibo radar'                 : 'Arecibo Observatory',
    'framing camera'                : 'Dawn',
    'gemini north telescope'        : 'Gemini North Telescope',
    'gemini south telescope'        : 'Gemini South Telescope',
    'hale telescope'                : 'Palomar Observatory',
    'hubble space telescope'        : 'Hubble Space Telescope',
    'keck telescope'                : 'W. M. Keck Telescope',
    'moon mineralogy mapper'        : 'Chandrayaan-1',
    'neocam sensor'                 : 'Near-Earth Object Camera',
    'neocam'                        : 'Near-Earth Object Camera',
    'photopolarimeter/radiometer'   : 'Galileo Orbiter',
    'samuel oschin telescope'       : 'Palomar Observatory',
    'solid state imaging (ssi)'     : 'Galileo Orbiter',
    'surface stereo imager (ssi)'   : 'Phoenix Mars Lander',
    'w. m. keck telescope'          : 'W. M. Keck Telescope',
    'wise telescope'                : 'NEOWISE',
    'la sagra sky survey (lsss)'    : 'La Sagra Observatory',
    'la sagra sky survey'           : 'La Sagra Observatory',
    'lsss'                          : 'La Sagra Observatory',

}

################################################################################

