################################################################################
# dicts/INSTRUMENT_FULL_NAMES.py
#
# Usage:
#   from INSTRUMENT_FULL_NAMES import INSTRUMENT_FULL_NAMES
#
# INSTRUMENT_FULL_NAMES is a dictionary that translates the lower-case name or
# abbreviation of an instrument into its full name.
################################################################################

INSTRUMENT_FULL_NAMES = {
    'acrim3'                                    : 'Active Cavity Irradiance Monitor 3 (ACRIM 3)',
    'acs'                                       : 'Advanced Camera for Surveys (ACS)',
    'advanced camera for surveys'               : 'Advanced Camera for Surveys (ACS)',
    'alice uvs'                                 : 'Alice Ultravilet Spectrometer',
    'alice'                                     : 'Alice Ultravilet Spectrometer',
    'alpha particle x-ray spectrometer (msl)'   : 'Alpha Particle X-Ray Spectrometer (APXS)',
    'alpha particle x-ray spectrometer'         : 'Alpha Particle X-Ray Spectrometer (APXS)',
    'alpha particle x-ray spectrometer'         : 'Alpha Particle X-Ray Spectrometer (APXS)',
    'alt'                                       : 'Altimetry (ALT)',
    'altimetry'                                 : 'Altimetry (ALT)',
    'altimetry (alt)'                           : 'Altimetry (ALT)',
    'apss'                                      : 'Auxiliary Payload Subsystem (APSS)',
    'apxs'                                      : 'Alpha Particle X-Ray Spectrometer (APXS)',
    'arecibo observatory'                       : 'Arecibo Radar',
    'arecibo radar data'                        : 'Arecibo Radar',
    'aster'                                     : 'Advanced Spaceborne Thermal Emission and Reflection Radiometer (ASTER)',
    'atmospheric structure / meteorology instrument': 'Atmospheric Structure Instrument/Meteorology Package (ASI/MET)',
    'autonomous navigation system'              : 'Autonomous Navigation (AutoNav)',        # Deep Impact
    'cda'                                       : 'Cosmic Dust Analzer (CDA)',
    'cfht'                                      : 'Canada-France-Hawaii Telescope (CFHT)',
    'chandra x-ray telescope'                   : 'Science Instrument Module (SIM)',
    'chemcam'                                   : 'Chemistry & Camera (ChemCam)',
    'chemin'                                    : 'Chemistry & Mineralogy X-Ray Diffraction (CheMin)',
    'chimera'                                   : 'Collection and Handling for Interior Martian Rock Analysis (CHIMRA)',
    'chimra'                                    : 'Collection and Handling for Interior Martian Rock Analysis (CHIMRA)',
    'cida'                                      : 'Cometary and Interstellar Dust Analyzer (CIDA)',
    'cirs'                                      : 'Composite Infrared Spectrometer (CIRS)',
    'civa'                                      : 'Comet Infrared and Visible Analyser (CIVA)',
    'comet infrared and visible analyser (civa)': 'Comet Infrared and Visible Analyser (CIVA)',
    'composite infrared spectrometer'           : 'Composite Infrared Spectrometer (CIRS)',
    'context camera'                            : 'Context Camera (CTX)',
    'cosmic dust analyzer'                      : 'Cosmic Dust Analyzer (CDA)',
    'crism'                                     : 'Compact Reconnaissance Imaging Spectrometer for Mars (CRISM)',
    'crs'                                       : 'Cosmic Ray Subsystem (CRS)',
    'ctx'                                       : 'Context Camera (CTX)',
    'dan'                                       : 'Dynamic Albedo of Neutrons (DAN)',
    'deep space network'                        : 'Goldstone Solar System Radar',
    'descent imager/spectral radiometer'        : 'Descent Imager/Spectral Radiometer (DISR)',
    'dfmi'                                      : 'Dust Flux Monitor Instrument (DFMI)',
    'dse'                                       : 'Dynamic Science Experiment (DSE)',
    'dsn'                                       : 'Goldstone Solar System Radar',
    'dual technique magnetometer'               : 'Magnetometer',
    'dynamic albedo of neutrons'                : 'Dynamic Albedo of Neutrons (DAN)',
    'e-themis'                                  : 'Europa Thermal Emission Imaging System (E-THEMIS)',
    'eis'                                       : 'Europa Imaging System (EIS)',
    'epps'                                      : 'Energetic Particle and Plasma Spectrometer (EPPS)',
    'europa-uvs'                                : 'Europa Ultraviolet Spectrograph (Europa-UVS)',
    'faint object camera'                       : 'Faint Object Camera (FOC)',
    'fips'                                      : 'Fast Imaging Plasma Spectrometer (FIPS)',
    'foc'                                       : 'Faint Object Camera (FOC)',
    'framing camera'                            : 'Framing Camera (FC)',                                # Dawn
    'gamma ray spectrometer - neutron spectrometer': 'Gamma Ray Spectrometer (GRS)',
    'gamma ray spectrometer suite'              : 'Gamma Ray Spectrometer (GRS)',
    'gamma ray spectrometer'                    : 'Gamma Ray Spectrometer (GRS)',
    'Gamma Ray and Neutron Spectrometer (GRNS)' : 'Gamma Ray and Neutron Spectrometer (GRNS)',          # Psyche
    'Gamma Ray/Neutron Spectrometer (GRNS)'     : 'Gamma Ray and Neutron Spectrometer (GRNS)',          # Psyche
    'grns'                                      : 'Gamma Ray and Neutron Spectrometer (GRNS)',
    'grs'                                       : 'Gamma Ray Spectrometer (GRS)',
    'hale telescope 200-inch'                   : 'Hale Telescope',
    'hazarc camera'                             : 'Hazard Camera (Hazcam)',
    'hazard avoidance camera (m2020)'           : 'Hazard Avoidance Camera',
    'hazcam (msl)'                              : 'Hazard Camera (Hazcam)',
    'hazcam (msl)'                              : 'Hazard Camera (Hazcam)',
    'hazcam (msl)'                              : 'Hazcam',
    'hazcam'                                    : 'Hazard Camera (Hazcam)',
    'heat and physical properties package'      : 'Heat and Physical Properties Package (HP3)',
    'hifi'                                      : 'Heterodyne Instrument for the Far Infrared (HIFI)',  # Herschel Space Observatory
    'high resolution instrument (hri)'          : 'High Resolution Instrument (HRI)',                   # Deep Impact
    'high resolution stereo camera'             : 'High Resolution Stereo Camera (HRSC)',
    'hirise'                                    : 'High Resolution Imaging Science Experiment (HiRISE)',
    'hp3'                                       : 'Heat Flow and Physical Properties Package (HP3)',
    'hri'                                       : 'High Resolution Instrument (HRI)',                   # Deep Impact
    'hrsc'                                      : 'High Resolution Stereo Camera (HRSC)',
    'hubble space telescope'                    : 'Advanced Camera for Surveys (ACS)',                  # Deep Impact support
    'icc'                                       : 'Instrument Context Camera (ICC)',
    'icemag'                                    : 'Interior Characterization of Europa using Magnetometry (ICEMAG)',
    'ida'                                       : 'Instrument Deployment Arm (IDA)',
    'idc'                                       : 'Instrument Deployment Camera (IDC)',
    'imager for mars pathfinder'                : 'Imager for Mars Pathfinder (IMP)',
    'imaging radar'                             : 'Imaging Radar',
    'imaging science subsystem - narrow angle'  : 'Imaging Science Subsystem (ISS)',
    'imaging science subsystem - wide angle'    : 'Imaging Science Subsystem (ISS)',
    'imaging science subsystem'                 : 'Imaging Science Subsystem (ISS)',
    'imaging science subsystem'                 : 'Imaging Science Subsystem (ISS)',
    'imaging ultraviolet spectrograph'          : 'Imaging Ultraviolet Spectrograph (IUVS)',
    'impactor targeting sensor (its)'           : 'Impactor Targeting Sensor (ITS)',                    # Deep Impact
    'infrared array camera (irac)'              : 'Infrared Array Camera (IRAC)',                       # Spitzer
    'infrared spectrometer (irs)'               : 'Infrared Spectrometer (IRS)',                        # Deep Impact
    'inms'                                      : 'Ion and Neutral Mass Spectrometer (INMS)',
    'ion and neutral mass spectrometer'         : 'Ion and Neutral Mass Spectrometer (INMS)',
    'ion engine'                                : 'Ion Engine',                                         # Deep Space 1
    'irac'                                      : 'Infrared Array Camera (IRAC)',
    'irs'                                       : 'Infrared Spectrograph (IRS)',
    'irtf'                                      : 'Infrared Telescope Facility (IRTF)',
    'iss - narrow angle'                        : 'Imaging Science Subsystem (ISS)',
    'iss - wide angle'                          : 'Imaging Science Subsystem (ISS)',
    'iss'                                       : 'Imaging Science Subsystem (ISS)',
    'jiram'                                     : 'Juno Infrared Auroral Mapper (JIRAM)',
    'keck telescope'                            : 'W. M. Keck Telescope',
    "kitt peak observatory's 2.1 m telescope"   : 'KPNO 2.1-meter Telescope',
    'la sagra sky survey'                       : 'La Sagra Sky Survey (LSSS)',
    'larri'                                     : 'Laser RetroReflector for InSight (LaRRI)',
    'laser altimeter'                           : 'Mars Orbiter Laser Altimeter (MOLA)',
    'laser rangefinder'                         : 'NEAR Laser Rangefinder (NLR)',
    'lcam'                                      : 'Lander Vision System Camera (LCAM)',
    'leisa'                                     : 'Linear Etalon Imaging Spectral Array (LEISA)',
    'lorri'                                     : 'Long Range Reconnaissance Imager (LORRI)',
    'low-energy charged particle instrument'    : 'Low-Energy Charged Particle Instrument (LECP)',
    'lvs'                                       : 'Lander Vision System (LVS)',
    "l'lorri"                                   : "Lucy-Long Range Reconnaissance Imager (L'LORRI)",
    "l'mvic"                                    : "Lucy-Multispectral Visible Imaging Camera (L'MVIC)",
    "l'tes"                                     : "Lucy-Thermal Infrared Spectrometer (L'TES)",
    'mag'                                       : 'Magnetometer',
    'magnetometer (mag)'                        : 'Magnetometer',
    'magnetometer'                              : 'Magnetometer',
    'mahli'                                     : 'Mars Hand Lens Imager (MAHLI)',
    'marci'                                     : 'Mars Color Imager (MARCI)',
    'mardi'                                     : 'Mars Descent Imager (MARDI)',
    'marie'                                     : 'Mars Radiation Environment Experiment (MARIE)',
    'mars advanced radar for subsurface and ionospheric sounding': 'Mars Advanced Radar for Subsurface and Ionosphere Sounding (MARSIS)',
    'mars descent imager'                       : 'Mars Descent Imager (MARDI)',
    'mars orbiter camer'                        : 'Mars Orbiter Camera (MOC)',
    'mars orbiter camera'                       : 'Mars Orbiter Camera (MOC)',
    'mars orbiter laser altimeter'              : 'Mars Orbiter Laser Altimeter (MOLA)',
    'mars radiation experiment'                 : 'Mars Radiation Environment Experiment (MARIE)',
    'marsis'                                    : 'Mars Advanced Radar for Subsurface and Ionosphere Sounding (MARSIS)',
    'mascs'                                     : 'Mercury Atmospheric and Surface Composition Spectrometer (MASCS)',
    'maspex'                                    : 'Mass Spectrometer for Planetary Exploration (MASPEX)',
    'mastcam-z'                                 : 'Mastcam-Z',
    'mastcam'                                   : 'Mast Camera (MastCam)',
    'mdis - narrow angle'                       : 'Mercury Dual Imaging System (MDIS)',                     # MESSENGER
    'mdis - wide angle'                         : 'Mercury Dual Imaging System (MDIS)',                     # MESSENGER
    'meca'                                      : 'Microscopy, Electrochemistry, and Conductivity Analyzer (MECA)',
    'meda'                                      : 'Mars Environmental Dynamics Analyzer (MEDA)',
    'medium resolution instrument (mri)'        : 'Medium Resolution Instrument (MRI)',                     # Deep Impact
    'mercury dual imaging system - narrow angle': 'Mercury Dual Imaging System (MDIS)',
    'mercury dual imaging system - wide angle'  : 'Mercury Dual Imaging System (MDIS)',
    'mercury dual imaging system'               : 'Mercury Dual Imaging System (MDIS)',
    'messenger magnetometer (mag)'              : 'Magnetometer',
    'met'                                       : 'Meteorological Station (MET)',
    'microscopic imager'                        : 'Microscopic Imager (MI)',
    'mimi'                                      : 'Magnetospheric Imaging Instrument (MIMI)',
    'mini-tes'                                  : 'Miniature Thermal Emission Spectrometer (Mini-TES)',
    'miniature integrated camera spectrometer'  : 'Miniature Integrated Camera Spectrometer (MICAS)',
    'miniature thermal emission spectrometer'   : 'Miniature Thermal Emission Spectrometer (Mini-TES)',
    'mips'                                      : 'Multiband Imaging Photometer for Spitzer (MIPS)',
    'miro'                                      : 'Microwave Instrument for the Rosetta Orbiter (MIRO)',
    'mise'                                      : 'Mapping Imaging Spectrometer for Europa (MISE)',
    'misr'                                      : 'Multi-Angle Imaging SpectroRadiometer (MISR)',
    'mla'                                       : 'Mercury Laser Altimeter (MLA)',
    'moessbauer spectrometer'                   : 'Moessbauer Spectrometer (MB)',
    'mola'                                      : 'Mars Orbiter Laser Altimeter (MOLA)',
    'moxie'                                     : 'Mars Oxygen ISRU Experiment (MOXIE)',
    'mri'                                       : 'Medium Resolution Instrument (MRI)',                     # Deep Impact
    'multiband imaging photometer (mips)'       : 'Multiband Imaging Photometer (MIPS)',                    # Spitzer
    'multispectral visible imaging camera (mvic)': 'Multispectral Visible Imaging Camera (MVIC)',           # New Horizons
    'multi-angle imaging spectroradiometer'     : 'Multi-Angle Imaging SpectroRadiometer (MISR)',
    'multi-spectral imager'                     : 'Multi-Spectral Imager (MSI)',                            # Psyche
    'mvic'                                      : 'Multispectral Visible Imaging Camera (MVIC)',
    'mwr'                                       : 'Microwave Radiometer (MWR)',
    'navcam (msl)'                              : 'Navcam',
    'navcam (msl)'                              : 'Navigation Camera (Navcam)',
    'navcam'                                    : 'Navigation Camera (Navcam)',
    'navigation camera (m2020)'                 : 'Navigation Camera',
    'navigation camera'                         : 'Navigation Camera (Navcam)',
    'nc'                                        : 'Navigation Camera (NC)',
    'near infra-red mapping spectrometer'       : 'Near Infrared Mapping Spectrometer (NIMS)',
    'near infrared camera'                      : 'Imaging Science Subsystem (ISS)',
    'near infrared mapping spectrometer'        : 'Near Infrared Mapping Spectrometer (NIMS)',
    'near infrared spectrometer'                : 'Near-Infrared Spectrometer (NIS)',                       # NEAR
    'neocam'                                    : 'Near-Earth Object Camera (NEOCAM)',
    'neocam sensor'                             : 'Near-Earth Object Camera (NEOCAM)',
    'neutral gas and ion mass spectrometer'     : 'Neutral Gas and Ion Mass Spectrometer (NGIMS)',
    'neutron spectrometer'                      : 'Gamma Ray Spectrometer (GRS)',
    'ngims'                                     : 'Neutral Gas and Ion Mass Spectrometer (NGIMS)',
    'nicmos'                                    : 'Near Infrared Camera and Multi-Object Spectrometer (NICMOS)',
    'nims'                                      : 'Near-Infrared Mapping Spectrometer (NIMS)',
    'nis'                                       : 'Near-Infrared Spectrometer (NIS)',
    'nlr'                                       : 'NEAR Laser Rangefinder (NLR)',
    'omega'                                     : 'Visible and Infrared Mineralogical Mapping Spectrometer (OMEGA)',
    'optical microscope'                        : 'Microscopy, Electrochemistry, and Conductivity Analyzer (MECA)',
    'orad'                                      : 'Surface Radar Mapper (ORAD)',
    'oschin schmidt telescope'                  : 'Samuel Oschin Telescope',
    'osiris'                                    : 'Optical, Spectrocopic and Infrared Remote Imaging System (OSIRIS)',      # Rosetta
    'pacs'                                      : 'Photodetector Array Camera & Spectrometer (PACS)',
    'pancam'                                    : 'Panoramic Camera (Pancam)',
    'panoramic camera'                          : 'Panoramic Camera (Pancam)',
    'photopolarimeter-radiometer'               : 'Photopolarimeter-Radiometer (PPR)',
    'photopolarimeter subsystem'                : 'Photopolarimeter Subsystem (PPS)',
    'pims'                                      : 'Plasma Instrument for Magnetic Sounding (PIMS)',
    'pixl'                                      : 'Planetary Instrument for X-ray Lithography (PIXL)',
    'plasma spectrometer'                       : 'Radio and Plasma Wave Science Instrument (RPWS)',
    'plasma wave instrument'                    : 'Plasma Wave Instrument (PWS)',
    'pls'                                       : 'Plasma Science Experiment (PLS)',
    'pps'                                       : 'Photopolarimeter Subsystem (PPS)',
    'rad'                                       : 'Radiation Assessment Detector (RAD)', # or 'Radiometry' for Magellan
    'radar mapper'                              : 'Radar Mapper',
    'radiation assessment detector'             : 'Radiation Assessment Detector (RAD)',
    'radio and plasma wave science instrument'  : 'Radio and Plasma Wave Science Instrument (RPWS)',
    'radio science subsystem'                   : 'Radio Science Subsystem (RSS)',
    'radio science'                             : 'Radio Science (RS)',
    'radiometry'                                : 'Radiometry (RAD)',
    'ralph color imager'                        : 'Multispectral Visible Imaging Camera (MVIC)',
    'ralph'                                     : 'Visible/Infrared Imager (RALPH)',
    'reason'                                    : 'Radar for Europa Assessment and Sounding: Ocean to Near-surface (REASON)',
    'rems'                                      : 'Rover Environmental Monitoring Station (REMS)',
    'rex'                                       : 'Radio Science Experiment (REX)',
    'rime'                                      : 'Radar for Icy Moon Exploration (RIME)',
    'rimfax'                                    : "Radar Imager for Mars' subsurface experiment (RIMFAX)",
    'rise'                                      : 'Rotation and Interior Structure Experiment (RISE)',
    'robotic arm (msl)'                         : 'Robotic Arm',
    'robotic arm camera'                        : 'Robotic Arm Camera (RAC)',
    'robotic arm'                               : 'Robotic Arm',
    'rolis'                                     : 'Rosetta Lander Imaging System (ROLIS)',
    'rosetta navcam'                            : 'Navigation Camera (Navcam)',                             # Rosetta Orbiter
    'rosetta lander imaging system (rolis)'     : 'Rosetta Lander Imaging System (ROLIS)',
    'rosina'                                    : 'Rosetta Orbiter Spectrometer for Ion and Neutral Analysis (ROSINA)',
    'rss'                                       : 'Radioscience Subsystem (RSS)',
    'sam'                                       : 'Sample Analysis at Mars (SAM)',
    'sar'                                       : 'Synthetic Aperture Radar (SAR)',
    'seis'                                      : 'Seismic Experiment for Interior Structure (SEIS)',
    'sherloc'                                   : 'Scanning Habitable Environments with Raman & Luminescence for Organics and Chemicals (SHERLOC)',
    'solid state imaging (ssi)'                 : 'Solid State Imaging (SSI)',
    'solid-state imaging'                       : 'Solid-State Imaging (SSI)',
    'spizter space telescope'                   : 'Spitzer Space Telescope',
    'sru'                                       : 'Stellar Reference Unit (SRU)',
    'ssc'                                       : 'Stardust Sample Collection (SSC)',
    'ssi'                                       : 'Solid-State Imaging (SSI)',
    'stardust navigation camera'                : 'Stardust Navigation Camera (NC)',
    'suda'                                      : 'Surface Dust Analyzer (SUDA)',
    'supercam'                                  : 'SuperCam',
    'surface radar mapper'                      : 'Surface Radar Mapper (ORAD)',
    'surface stereo imager'                     : 'Surface Stereo Imager (SSI)',
    'swap'                                      : 'Solar Wind Around Pluto (SWAP)',
    'synthetic-aperture radar (sar)'            : 'Synthetic Aperture Radar (SAR)',
    'tega'                                      : 'Thermal and Evolved Gas Analyzer (TEGA)',
    'themis'                                    : 'Thermal Emission Imaging System (THEMIS)',
    'thermal and electrical conductivity probe' : 'Thermal and Electrical Conductivity Probe (TECA)',
    'thermal emission imaging system'           : 'Thermal Emission Imaging System (THEMIS)',
    'thermal emission spectrometer'             : 'Thermal Emission Spectrometer (TES)',
    'trace gas orbiter'                         : 'ExoMars Trace Gas Orbiter (TGO)',
    'trappist'                                  : 'Transiting Planets and Planetesimals Small Telescope (TRAPPIST)',
    'twins'                                     : 'Temperature and Wind for InSight (TWINS)',
    'ultraviolet imaging spectrograph'          : 'Ultraviolet Imaging Spectrometer (UVIS)',
    'uvis'                                      : 'Ultraviolet Imaging Spectrometer (UVIS)',
    'uvs'                                       : 'Ultraviolet Spectrometer (UVS)',
    'val'                                       : 'Venus Analytic Laboratory (VAL)',
    'vasi'                                      : 'Venus Atmospheric Structure Investigation (VASI)',
    'vem'                                       : 'Venus Emissivity Mapper (VEM)',
    'vendi'                                     : 'Venus Descent Imager (VenDI)',
    'very large telescope (vlt)'                : 'Very Large Telescope (VLT)',
    'vlt'                                       : 'Very Large Telescope (VLT)',
    'vg imaging science subsystem'              : 'Imaging Science Subsystem (ISS)',
    'vg iss - narrow angle'                     : 'Imaging Science Subsystem (ISS)',
    'vg iss - wide angle'                       : 'Imaging Science Subsystem (ISS)',
    'vims'                                      : 'Visual and Infrared Mapping Spectrometer (VIMS)',
    'vir'                                       : 'Visible and Infrared Spectrometer (VIR)',                    # Dawn
    'virtis'                                    : 'Visible and Infrared Thermal Imaging Spectrometer (VIRTIS)',
    'visar'                                     : 'Venus Interferometric Synthetic Aperture Radar (VISAR)',
    'visible and infrared mineralogical mapping spectrometer' : 'Visible and Infrared Mineralogical Mapping Spectrometer (OMEGA)',
    'visual and infrared mapping spectrometer'  : 'Visual and Infrared Mapping Spectrometer (VIMS)',
    'visual and infrared spectrometer (vir)'    : 'Visible and Infrared Spectrometer (VIR)',                    # Dawn
    'vlt'                                       : 'Very Large Telescope (VLT)',
    'vms'                                       : 'Venus Mass Spectrometer (VMS)',
    'vtls'                                      : 'Venus Tunable Laser Spectrometer (VTLS)',
    'watson'                                    : 'Wide Angle Topographic Sensor for Operations and Engineering (WATSON)',  # Perseverance
    'wfc3'                                      : 'Wide Field Camera 3 (WFC3)',
    'wfcp3'                                     : 'Wide Field Camera 3 (WFC3)',
    'wfpc2'                                     : 'Wide Field/Planetary Camera 2 (WFPC2)',
    'wide field camera 3'                       : 'Wide Field Camera 3 (WFC3)',
    'wide field planetary camera 2'             : 'Wide Field/Planetary Camera 2 (WFPC2)',
    'wise'                                      : 'NEOWISE Telescope',
    'wise telescope'                            : 'NEOWISE Telescope',
    'xrs'                                       : 'X-Ray Spectrometer (XRS)',
    'ztf'                                       : 'Zwicky Transient Facility (ZTF)',
}

################################################################################
