################################################################################
# dicts/MISSION_FULL_NAMES.py
#
# Usage:
#   from MISSION_FULL_NAMES import MISSION_FULL_NAMES
#
# MISSION_FULL_NAMES is a dictionary that translates the lower-case name or
# abbreviation of a mission into its full name.
################################################################################

from .HOST_INFO import HOST_INFO

MISSION_FULL_NAMES = {
    '2001 mars odyssey'                 : '2001 Mars Odyssey',
    'acrimsat'                          : 'Active Cavity Irradiance Monitor Satellite (AcrimSat)',
    'arm'                               : 'Asteroid Redirect Mission (ARM)',
    'canberra deep space network (dsn)' : 'Deep Space Network (DSN)',
    'chandra x-ray observatory'         : 'Chandra X-ray Observatory (CXO)',
    'cxo'                               : 'Chandra X-ray Observatory (CXO)',
    'css'                               : 'Catalina Sky Survey (CSS)',
    'dart'                              : 'Double Asteroid Redirect Test (DART)',
    'davinci'                           : 'DAVINCI+',
    'davinci+'                          : 'DAVINCI+',
    'deep impact  (dixi)'               : 'Deep Impact',
    'deep impact (dixi)'                : 'Deep Impact',
    'deep space 1'                      : 'Deep Space 1 (DS1)',
    'deep space 1 (ds1)'                : 'Deep Space 1 (DS1)',
    'ds1'                               : 'Deep Space 1 (DS1)',
    'dsn'                               : 'Deep Space Network (DSN)',
    'dspse'                             : 'Deep Space Program Science Experiment (DSPSE)',
    'epoxi'                             : 'Deep Impact',
    'goldstone deep space network (dsn)': 'Deep Space Network (DSN)',
    'hst'                               : 'Hubble Space Telescope (HST)',
    'hubble space telescope'            : 'Hubble Space Telescope (HST)',
    'insight'                           : 'InSight',
    'james webb space telescope'        : 'James Webb Space Telescope (JWST)',
    'juice'                             : 'Jupiter Icy Moons Explorer (JUICE)',
    'jwst'                              : 'James Webb Space Telescope (JWST)',
    'kepler spacecraft'                 : 'Kepler',
    'marco'                             : 'Mars Cube One (MarCO)',
    'mariner 10'                        : 'Mariner',
    'mariner 2'                         : 'Mariner',
    'mariner mars 1964 (mariner 4)'     : 'Mariner',
    'mariner mars 1969 (mariner 7)'     : 'Mariner',
    'mariner mars 1971 (mariner 9)'     : 'Mariner',
    'mariner mars 1971 (mariner 9)'     : 'Mariner',
    'mariner venus mercury (mariner 10)': 'Mariner',
    'mars 2020 rover'                   : 'Mars 2020',
    'mars 2020 project'                 : 'Mars 2020',
    'mars atmosphere and volatile evolution (maven)' : 'Mars Atmosphere and Volatile Evolution (MAVEN)',
    'mars exploration rover'            : 'Mars Exploration Rover (MER)',
    'mars express'                      : 'Mars Express (MEX)',
    'mars global surveyor orbiter'      : 'Mars Global Surveyor (MGS)',
    'mars global surveyor'              : 'Mars Global Surveyor (MGS)',
    'mars odyssey'                      : '2001 Mars Odyssey',
    'mars pathfinder'                   : 'Mars Pathfinder (MPF)',
    'mars reconnaissance orbiter'       : 'Mars Reconnaissance Orbiter (MRO)',
    'mars science laboratory'           : 'Mars Science Laboratory (MSL)',
    'maven'                             : 'Mars Atmosphere and Volatile Evolution (MAVEN)',
    'mer'                               : 'Mars Exploration Rover (MER)',
    'mgs'                               : 'Mars Global Surveyor (MGS)',
    'mpf'                               : 'Mars Pathfinder (MPF)',
    'mro'                               : 'Mars Reconnaissance Orbiter (MRO)',
    'msl'                               : 'Mars Science Laboratory (MSL)',
    'msr'                               : 'Mars Sample Return (MSR)',
    'near earth asteroid rendezvous'    : 'NEAR Shoemaker',
    'near'                              : 'NEAR Shoemaker',
    'neocam'                            : 'Near-Earth Object Camera (NEOCam)',
    'opportunity (mer-b)'               : 'Mars Exploration Rover (MER)',
    'perseverance'                      : 'Mars 2020',
    'sdo'                               : 'Solar Dynamics Observatory (SDO)',
    'spirit (mer-a)'                    : 'Mars Exploration Rover (MER)',
    'spitzer telescope'                 : 'Spitzer Space Telescope',
    'stardustnext'                      : 'Stardust',
    'transiting planets and planetesimals small telescope': 'Transiting Planets and Planetesimals Small Telescope (TRAPPIST)',
    'trappist'                          : 'Transiting Planets and Planetesimals Small Telescope (TRAPPIST)',
    'viking 1'                          : 'Viking',
    'viking 2'                          : 'Viking',
    'voyager interstellar mission'      : 'Voyager',
    'wise'                              : 'Near-Earth Object Wide-field Infrared Survey Explorer (NEOWISE)',
    'neowise'                           : 'Near-Earth Object Wide-field Infrared Survey Explorer (NEOWISE)',
    'neowise telescope'                 : 'Near-Earth Object Wide-field Infrared Survey Explorer (NEOWISE)',
    'nrao'                              : 'National Radio Astronomy Observatory (NRAO)',
    'wfirst'                            : 'Wide-Field Infrared Survey Telescope (WFIRST)',
}

MISSION_FULL_NAMES.update({k:v[1] for (k,v) in HOST_INFO.items()})
