################################################################################
# dicts/SYSTEM_FROM_TARGET.py
#
# Usage:
#   from SYSTEM_FROM_TARGET import SYSTEM_FROM_TARGET
#
# SYSTEM_FROM_TARGET is a dictionary that translates the lower-case name or
# abbreviation of a target to a tuple containing its associated system name and
# target type.
################################################################################

SYSTEM_FROM_TARGET = {
    'earth'             : ('Earth', 'Earth'),
    'moon'              : ('Earth', 'Satellite'),

    'mars'              : ('Mars', 'Planet'),
    'phobos'            : ('Mars', 'Satellite'),
    'deimos'            : ('Mars', 'Satellite'),

    'jupiter'           : ('Jupiter', 'Planet'),
    'jupiter rings'     : ('Jupiter', 'Ring'),
    'main ring'         : ('Jupiter', 'Ring'),
    'halo'              : ('Jupiter', 'Ring'),
    'gossamer ring'     : ('Jupiter', 'Ring'),
    'adrastea'          : ('Jupiter', 'Satellite'),
    'metis'             : ('Jupiter', 'Satellite'),
    'amalthea'          : ('Jupiter', 'Satellite'),
    'thebe'             : ('Jupiter', 'Satellite'),
    'io'                : ('Jupiter', 'Satellite'),
    'europa'            : ('Jupiter', 'Satellite'),
    'ganymede'          : ('Jupiter', 'Satellite'),
    'callisto'          : ('Jupiter', 'Satellite'),
    'themisto'          : ('Jupiter', 'Satellite'),
    'leda'              : ('Jupiter', 'Satellite'),
    'himalia'           : ('Jupiter', 'Satellite'),
    'lysithea'          : ('Jupiter', 'Satellite'),
    'elara'             : ('Jupiter', 'Satellite'),
    'dia'               : ('Jupiter', 'Satellite'),
    'carpo'             : ('Jupiter', 'Satellite'),
    'euporie'           : ('Jupiter', 'Satellite'),
    'thelxinoe'         : ('Jupiter', 'Satellite'),
    'euanthe'           : ('Jupiter', 'Satellite'),
    'helike'            : ('Jupiter', 'Satellite'),
    'orthosie'          : ('Jupiter', 'Satellite'),
    'iocaste'           : ('Jupiter', 'Satellite'),
    'praxidike'         : ('Jupiter', 'Satellite'),
    'harpalyke'         : ('Jupiter', 'Satellite'),
    'mneme'             : ('Jupiter', 'Satellite'),
    'hermippe'          : ('Jupiter', 'Satellite'),
    'thyone'            : ('Jupiter', 'Satellite'),
    'ananke'            : ('Jupiter', 'Satellite'),
    'herse'             : ('Jupiter', 'Satellite'),
    'aitne'             : ('Jupiter', 'Satellite'),
    'kale'              : ('Jupiter', 'Satellite'),
    'taygete'           : ('Jupiter', 'Satellite'),
    'chaldene'          : ('Jupiter', 'Satellite'),
    'erinome'           : ('Jupiter', 'Satellite'),
    'aoede'             : ('Jupiter', 'Satellite'),
    'kallichore'        : ('Jupiter', 'Satellite'),
    'kalyke'            : ('Jupiter', 'Satellite'),
    'carme'             : ('Jupiter', 'Satellite'),
    'callirrhoe'        : ('Jupiter', 'Satellite'),
    'eurydome'          : ('Jupiter', 'Satellite'),
    'pasithee'          : ('Jupiter', 'Satellite'),
    'kore'              : ('Jupiter', 'Satellite'),
    'cyllene'           : ('Jupiter', 'Satellite'),
    'eukelade'          : ('Jupiter', 'Satellite'),
    'pasiphae'          : ('Jupiter', 'Satellite'),
    'hegemone'          : ('Jupiter', 'Satellite'),
    'arche'             : ('Jupiter', 'Satellite'),
    'isonoe'            : ('Jupiter', 'Satellite'),
    'sinope'            : ('Jupiter', 'Satellite'),
    'sponde'            : ('Jupiter', 'Satellite'),
    'autonoe'           : ('Jupiter', 'Satellite'),
    'megaclite'         : ('Jupiter', 'Satellite'),

    'saturn'            : ('Saturn', 'Planet'),
    'saturn rings'      : ('Saturn', 'Ring'),
    'a ring'            : ('Saturn', 'Ring'),
    'b ring'            : ('Saturn', 'Ring'),
    'c ring'            : ('Saturn', 'Ring'),
    'd ring'            : ('Saturn', 'Ring'),
    'e ring'            : ('Saturn', 'Ring'),
    'f ring'            : ('Saturn', 'Ring'),
    'g ring'            : ('Saturn', 'Ring'),
    'cassini division'  : ('Saturn', 'Gap'),
    'encke gap'         : ('Saturn', 'Gap'),
    'pan'               : ('Saturn', 'Satellite'),
    'daphnis'           : ('Saturn', 'Satellite'),
    'atlas'             : ('Saturn', 'Satellite'),
    'prometheus'        : ('Saturn', 'Satellite'),
    'pandora'           : ('Saturn', 'Satellite'),
    'epimetheus'        : ('Saturn', 'Satellite'),
    'janus'             : ('Saturn', 'Satellite'),
    'aegaeon'           : ('Saturn', 'Satellite'),
    'methone'           : ('Saturn', 'Satellite'),
    'anthe'             : ('Saturn', 'Satellite'),
    'pallene'           : ('Saturn', 'Satellite'),
    'telesto'           : ('Saturn', 'Satellite'),
    'calypso'           : ('Saturn', 'Satellite'),
    'dione'             : ('Saturn', 'Satellite'),
    'helene'            : ('Saturn', 'Satellite'),
    'polydeuces'        : ('Saturn', 'Satellite'),
    'mimas'             : ('Saturn', 'Satellite'),
    'enceladus'         : ('Saturn', 'Satellite'),
    'tethys'            : ('Saturn', 'Satellite'),
    'dione'             : ('Saturn', 'Satellite'),
    'rhea'              : ('Saturn', 'Satellite'),
    'titan'             : ('Saturn', 'Satellite'),
    'hyperion'          : ('Saturn', 'Satellite'),
    'iapetus'           : ('Saturn', 'Satellite'),
    'phoebe'            : ('Saturn', 'Satellite'),
    'kiviuq'            : ('Saturn', 'Satellite'),
    'ijiraq'            : ('Saturn', 'Satellite'),
    'paaliaq'           : ('Saturn', 'Satellite'),
    'skathi'            : ('Saturn', 'Satellite'),
    'albiorix'          : ('Saturn', 'Satellite'),
    'bebhionn'          : ('Saturn', 'Satellite'),
    'erriapus'          : ('Saturn', 'Satellite'),
    'skoll'             : ('Saturn', 'Satellite'),
    'siarnaq'           : ('Saturn', 'Satellite'),
    'tarqeq'            : ('Saturn', 'Satellite'),
    'greip'             : ('Saturn', 'Satellite'),
    'hyrrokkin'         : ('Saturn', 'Satellite'),
    'jarnsaxa'          : ('Saturn', 'Satellite'),
    'tarvos'            : ('Saturn', 'Satellite'),
    'mundilfari'        : ('Saturn', 'Satellite'),
    'bergelmir'         : ('Saturn', 'Satellite'),
    'narvi'             : ('Saturn', 'Satellite'),
    'suttungr'          : ('Saturn', 'Satellite'),
    'hati'              : ('Saturn', 'Satellite'),
    'farbauti'          : ('Saturn', 'Satellite'),
    'thrymr'            : ('Saturn', 'Satellite'),
    'aegir'             : ('Saturn', 'Satellite'),
    'bestla'            : ('Saturn', 'Satellite'),
    'fenrir'            : ('Saturn', 'Satellite'),
    'surtur'            : ('Saturn', 'Satellite'),
    'kari'              : ('Saturn', 'Satellite'),
    'ymir'              : ('Saturn', 'Satellite'),
    'loge'              : ('Saturn', 'Satellite'),
    'fornjot'           : ('Saturn', 'Satellite'),

    'uranus'            : ('Uranus', 'Planet'),
    'uranus rings'      : ('Uranus', 'Ring'),
    'zeta ring'         : ('Uranus', 'Ring'),
    'six ring'          : ('Uranus', 'Ring'),
    'five ring'         : ('Uranus', 'Ring'),
    'four ring'         : ('Uranus', 'Ring'),
    'alpha ring'        : ('Uranus', 'Ring'),
    'beta ring'         : ('Uranus', 'Ring'),
    'eta ring'          : ('Uranus', 'Ring'),
    'gamma ring'        : ('Uranus', 'Ring'),
    'delta ring'        : ('Uranus', 'Ring'),
    'lambda ring'       : ('Uranus', 'Ring'),
    'epsilon ring'      : ('Uranus', 'Ring'),
    'nu ring'           : ('Uranus', 'Ring'),
    'mu ring'           : ('Uranus', 'Ring'),
    'cordelia'          : ('Uranus', 'Satellite'),
    'ophelia'           : ('Uranus', 'Satellite'),
    'bianca'            : ('Uranus', 'Satellite'),
    'cressida'          : ('Uranus', 'Satellite'),
    'desdemona'         : ('Uranus', 'Satellite'),
    'juliet'            : ('Uranus', 'Satellite'),
    'portia'            : ('Uranus', 'Satellite'),
    'rosalind'          : ('Uranus', 'Satellite'),
    'cupid'             : ('Uranus', 'Satellite'),
    'belinda'           : ('Uranus', 'Satellite'),
    'perdita'           : ('Uranus', 'Satellite'),
    'puck'              : ('Uranus', 'Satellite'),
    'mab'               : ('Uranus', 'Satellite'),
    'miranda'           : ('Uranus', 'Satellite'),
    'ariel'             : ('Uranus', 'Satellite'),
    'umbriel'           : ('Uranus', 'Satellite'),
    'titania'           : ('Uranus', 'Satellite'),
    'oberon'            : ('Uranus', 'Satellite'),
    'francisco'         : ('Uranus', 'Satellite'),
    'caliban'           : ('Uranus', 'Satellite'),
    'stephano'          : ('Uranus', 'Satellite'),
    'trinculo'          : ('Uranus', 'Satellite'),
    'sycorax'           : ('Uranus', 'Satellite'),
    'margaret'          : ('Uranus', 'Satellite'),
    'prospero'          : ('Uranus', 'Satellite'),
    'setebos'           : ('Uranus', 'Satellite'),
    'ferdinand'         : ('Uranus', 'Satellite'),

    'neptune'           : ('Neptune', 'Planet'),
    'neptune rings'     : ('Neptune', 'Ring'),
    'adams ring'        : ('Neptune', 'Ring'),
    'lassell ring'      : ('Neptune', 'Ring'),
    'le verrier ring'   : ('Neptune', 'Ring'),
    'galle ring'        : ('Neptune', 'Ring'),
    'liberte'           : ('Neptune', 'Arc'),
    'egalite'           : ('Neptune', 'Arc'),
    'fraternite'        : ('Neptune', 'Arc'),
    'courage'           : ('Neptune', 'Arc'),
    'naiad'             : ('Neptune', 'Satellite'),
    'thalassa'          : ('Neptune', 'Satellite'),
    'despina'           : ('Neptune', 'Satellite'),
    'galatea'           : ('Neptune', 'Satellite'),
    'larissa'           : ('Neptune', 'Satellite'),
    's/2004 n 1'        : ('Neptune', 'Satellite'),
    'proteus'           : ('Neptune', 'Satellite'),
    'triton'            : ('Neptune', 'Satellite'),
    'nereid'            : ('Neptune', 'Satellite'),
    'halimede'          : ('Neptune', 'Satellite'),
    'sao'               : ('Neptune', 'Satellite'),
    'laomedeia'         : ('Neptune', 'Satellite'),
    'psamathe'          : ('Neptune', 'Satellite'),
    'neso'              : ('Neptune', 'Satellite'),

    'pluto'             : ('Pluto', 'Dwarf Planet'),
    'charon'            : ('Pluto', 'Satellite'),
    'styx'              : ('Pluto', 'Satellite'),
    'nix'               : ('Pluto', 'Satellite'),
    'kerberos'          : ('Pluto', 'Satellite'),
    'hydra'             : ('Pluto', 'Satellite'),

    'dactyl'            : ('243 Ida', 'Satellite'),

    'ceres'             : ('Asteroid Belt', 'Dwarf Planet'),
    'haumea'            : ('Asteroid Belt', 'Dwarf Planet'),
    'makemake'          : ('Asteroid Belt', 'Dwarf Planet'),
    'eris'              : ('Asteroid Belt', 'Dwarf Planet'),
    '136108 haumea'     : ('Kuiper Belt', 'Dwarf Planet'),
    '136199 eris'       : ('Kuiper Belt', 'Dwarf Planet'),
    '136472 makemake'   : ('Kuiper Belt', 'Dwarf Planet'),

    'tempel 1'          : ('Periodic Comets', 'Comet'),    # non-standard comet names
    'halley'            : ('Periodic Comets', 'Comet'),
}

################################################################################

