################################################################################
# dicts/TARGET_FULL_NAMES.py
#
# Usage:
#   from TARGET_FULL_NAMES import TARGET_FULL_NAMES
#
# TARGET_FULL_NAMES is a dictionary that translates the lower-case name or
# abbreviation of a target into (full name, target_type, system (if any)).
################################################################################

TARGET_FULL_NAMES = {
    'j rings'       : ('Jupiter Rings'          , 'Ring'        , 'Jupiter' ),
    's rings'       : ('Saturn Rings'           , 'Ring'        , 'Saturn'  ),
    's/2004 s 1'    : ('Methone'                , 'Satellite'   , 'Saturn'  ),
    's/2004 s 2'    : ('Pallene'                , 'Satellite'   , 'Saturn'  ),
    's/2004 s 3'    : ('F Ring'                 , 'Ring'        , 'Saturn'  ),
    's/2004 s 5'    : ('Polydeuces'             , 'Satellite'   , 'Saturn'  ),
    's/2004 s 6'    : ('F Ring'                 , 'Ring'        , 'Saturn'  ),
    's/2005 s 1'    : ('Anthe'                  , 'Satellite'   , 'Saturn'  ),
    's/2008 s 1'    : ('Aegaeon'                , 'Satellite'   , 'Saturn'  ),
    'u rings'       : ('Uranus Rings'           , 'Ring'        , 'Uranus'  ),
    'n rings'       : ('Neptune Rings'          , 'Ring'        , 'Neptune' ),
    'moon'          : ('Moon'                   , 'Satellite'   , 'Earth'   ),

    '&scaron;teins' : ('2867 &Scaron;teins'     , 'Asteroid', 'Main Belt'),
    '1719 jens'     : ('1719 Jens'              , 'Asteroid', 'Main Belt'),
    'annefrank'     : ('5535 Annefrank'         , 'Asteroid', 'Main Belt'),
    'braille'       : ('9969 Braille'           , 'Asteroid', 'Main Belt'),
    '1992 kd'       : ('9969 Braille'           , 'Asteroid', 'Main Belt'),
    'ceres'         : ('1 Ceres'                , 'Asteroid', 'Main Belt'),
    'euphrosyne'    : ('31 Euphrosyne'          , 'Asteroid', 'Main Belt'),
    'ganesha'       : ('2415 Ganesa'            , 'Asteroid', 'Main Belt'),
    'gaspra'        : ('951 Gaspra'             , 'Asteroid', 'Main Belt'),
    'ida'           : ('243 Ida'                , 'Asteroid', 'Main Belt'),
    'itokawa'       : ('25143 Itokawa'          , 'Asteroid', 'Main Belt'),
    'kleopatra'     : ('216 Kleopatra'          , 'Asteroid', 'Main Belt'),
    'klotho'        : ('97 Klotho'              , 'Asteroid', 'Main Belt'),
    'lina'          : ('468 Lina'               , 'Asteroid', 'Main Belt'),
    'lutetia'       : ('21 Lutetia'             , 'Asteroid', 'Main Belt'),
    'malala'        : ('316201 Malala'          , 'Asteroid', 'Main Belt'),
    '2010 ml48'     : ('316201 Malala'          , 'Asteroid', 'Main Belt'),
    'masursky'      : ('2685 Masursky'          , 'Asteroid', 'Main Belt'),
    'mathilde'      : ('253 Mathilde'           , 'Asteroid', 'Main Belt'),
    'naozane'       : ('5238 Naozane'           , 'Asteroid', 'Main Belt'),
    'pallas'        : ('2 Pallas'               , 'Asteroid', 'Main Belt'),
    'psyche'        : ('16 Psyche'              , 'Asteroid', 'Main Belt'),
    'ryugu'         : ('162173 Ryugu'           , 'Asteroid', 'Main Belt'),
    'steins'        : ('2867 &Scaron;teins'     , 'Asteroid', 'Main Belt'),
    'toutatis'      : ('4179 Toutatis'          , 'Asteroid', 'Main Belt'),
    'vesta'         : ('4 Vesta'                , 'Asteroid', 'Main Belt'),
    '2002 jf56'     : ('132524 APL'             , 'Asteroid', 'Main Belt'),

    'dactyl'        : ('243 Ida I (Dactyl)'     , 'Satellite', '243 Ida' ),

    'don quixote'   : ('3552 Don Quixote'       , 'Asteroid', 'Near Earth Objects'),
    'eros'          : ('433 Eros'               , 'Asteroid', 'Near Earth Objects'),
    'bennu'         : ('101955 Bennu'           , 'Asteroid', 'Near Earth Objects'),
    '1999 rq36'     : ('101955 Bennu'           , 'Asteroid', 'Near Earth Objects'),
    '1994 cc'       : ('(136617) 1994 CC'       , 'Asteroid', 'Near Earth Objects'),
    '1998 kn3'      : ('(387505) 1998 KN3'      , 'Asteroid', 'Near Earth Objects'),
    '1998 qe2'      : ('(285263) 1998 QE2'      , 'Asteroid', 'Near Earth Objects'),
    '1998 wt24'     : ('(33342) 1998 WT24'      , 'Asteroid', 'Near Earth Objects'),
    '1999 jd6'      : ('(85989) 1999 JD6'       , 'Asteroid', 'Near Earth Objects'),
    '2001 fo32'     : ('(231937) 2001 FO32'     , 'Asteroid', 'Near Earth Objects'),
    '2003 sd2020'   : ('(163899) 2003 SD220'    , 'Asteroid', 'Near Earth Objects'),
    '2003 sd220'    : ('(163899) 2003 SD220'    , 'Asteroid', 'Near Earth Objects'),
    '2005 wk4'      : ('(277475) 2005 WK4'      , 'Asteroid', 'Near Earth Objects'),
    '2005 yu55'     : ('(308635) 2005 YU55'     , 'Asteroid', 'Near Earth Objects'),
    '2007 pa8'      : ('(214869) 2007 PA8'      , 'Asteroid', 'Near Earth Objects'),
    '2010 ab78'     : ('2010 AB78'              , 'Asteroid', 'Near Earth Objects'),
    '2010 tk7'      : ('2010 TK7'               , 'Asteroid', 'Near Earth Objects'),
    '2011 md'       : ('2011 MD'                , 'Asteroid', 'Near Earth Objects'),
    '2011 uw158'    : ('(436724) 2011 UW158'    , 'Asteroid', 'Near Earth Objects'),
    '2012 da14'     : ('367943 Duende'          , 'Asteroid', 'Near Earth Objects'),
    '2013 et'       : ('2013 ET'                , 'Asteroid', 'Near Earth Objects'),
    '2013 yp139'    : ('2013 YP139'             , 'Asteroid', 'Near Earth Objects'),
    '2014 aa'       : ('2014 AA'                , 'Asteroid', 'Near Earth Objects'),
    '2014 dx110'    : ('2014 DX110'             , 'Asteroid', 'Near Earth Objects'),
    '2014 ec'       : ('2014 EC'                , 'Asteroid', 'Near Earth Objects'),
    '2014 hq124'    : ('2014 HQ124'             , 'Asteroid', 'Near Earth Objects'),
    '2014 jo25'     : ('2014 JO25'              , 'Asteroid', 'Near Earth Objects'),
    '2015 tb145'    : ('2015 TB145'             , 'Asteroid', 'Near Earth Objects'),
    '2016 aj193'    : ('2016 AJ193'             , 'Asteroid', 'Near Earth Objects'),
    '2016 wf9'      : ('2016 WF9'               , 'Asteroid', 'Near Earth Objects'),
    '2017 bq6'      : ('2017 BQ6'               , 'Asteroid', 'Near Earth Objects'),
    '2017 ye5'      : ('2017 YE5'               , 'Asteroid', 'Near Earth Objects'),
    '2018 la'       : ('2018 LA'                , 'Asteroid', 'Near Earth Objects'),
    '2020 qg'       : ('2020 QG'                , 'Asteroid', 'Near Earth Objects'),
    '2021 pj1'      : ('2021 PJ1'               , 'Asteroid', 'Near Earth Objects'),

    'eris'          : ('136199 Eris'            , 'KBO', 'Kuiper Belt'),
    'haumea'        : ('136108 Haumea'          , 'KBO', 'Kuiper Belt'),
    'makemake'      : ('136472 Makemake'        , 'KBO', 'Kuiper Belt'),
    '2014 mu69'     : ('486958 Arrokoth'        , 'KBO', 'Kuiper Belt'),
    'sedna'         : ('90377 Sedna'            , 'KBO', 'Kuiper Belt'),
    'ultima thule'  : ('486958 Arrokoth'        , 'KBO', 'Kuiper Belt'),
    '2003 ub313'    : ('136199 Eris'            , 'KBO', 'Kuiper Belt'),
    'quaoar'        : ('50000 Quaoar'           , 'KBO', 'Kuiper Belt'),

    'hip 79124 b'   : ('HIP 79124'              , 'Exoplanet'   , 'HIP 79124'),
    'kepler-22b'    : ('Kepler-22'              , 'Exoplanet'   , 'Kepler-22'),
    'hd 189733b'    : ('HD 189733'              , 'Exoplanet'   , 'HD 189733'),
    'hd 149026b'    : ('HD 149026'              , 'Exoplanet'   , 'HD 149026'),

    'protostellar disk l1157':  ('L1157'        , 'Exoplanet'   , 'L1157'),

    'borrelly'              : ('19P/Borrelly'               , 'Comet', 'Periodic Comets'),
    'churyumov-gerasimenko' : ('67P/Churyumov-Gerasimenko'  , 'Comet', 'Periodic Comets'),
    'encke'                 : ('2P/Encke'                   , 'Comet', 'Periodic Comets'),
    'giacobini-zinner'      : ('21P/Giacobini-Zinner'       , 'Comet', 'Periodic Comets'),
    'grigg-skjellerup'      : ('26P/Grigg-Skjellerup'       , 'Comet', 'Periodic Comets'),
    'hale-bopp'             : ('C/1995 O1 (Hale-Bopp)'      , 'Comet', ''               ),
    'halley'                : ('1P/Halley'                  , 'Comet', 'Periodic Comets'),
    'hartley 2'             : ('103P/Hartley'               , 'Comet', 'Periodic Comets'),
    '103p/hartley 2'        : ('103P/Hartley'               , 'Comet', 'Periodic Comets'),
    'holmes'                : ('17P/Holmes'                 , 'Comet', 'Periodic Comets'),
    'hyakutake'             : ('C/1996 B2 (Hyakutake)'      , 'Comet', ''               ),
    'ison'                  : ('C/2012 S1 (ISON)'           , 'Comet', ''               ),
    'schwassmann-wachmann 2': ('31P/Schwassmann-Wachmann'   , 'Comet', 'Periodic Comets'),
    'schwassmann-wachmann 3': ('73P/Schwassmann-Wachmann'   , 'Comet', 'Periodic Comets'),
    'schwassmann-wachmann i': ('29P/Schwassmann-Wachmann'   , 'Comet', 'Periodic Comets'),
    'shoemaker-levy 9'      : ('Shoemaker-Levy 9'           , 'Comet', ''               ),
    'sl-9'                  : ('Shoemaker-Levy 9'           , 'Comet', ''               ),
    'sl9'                   : ('Shoemaker-Levy 9'           , 'Comet', ''               ),
    'tempel 1'              : ('9P/Tempel'                  , 'Comet', 'Periodic Comets'),
    'wild 2'                : ('81P/Wild'                   , 'Comet', 'Periodic Comets'),
    'c/2019 q4'             : ('2I/Borisov'                 , 'Comet', 'Interstellar Comets'),
}

# Always key a target by its actual full name too
for info in TARGET_FULL_NAMES.values():
    TARGET_FULL_NAMES[info[0].lower()] = info

################################################################################
