################################################################################
# piapage/BACKGROUND_STRINGS.py
#
# This is a list of character strings that might appear in a paragraph of the
# caption. If any of these is a substring of the caption, then the whole
# paragraph is declared to be background information.
#
# Usage:
#   from background_strings import BACKGROUND_STRINGS
#
################################################################################

BACKGROUND_STRINGS = [
    "(NIMS) on the Galileo spacecraft imaged",
    "A division of Caltech in Pasadena, California, NASA",
    "A joint effort between",
    "a joint mission of the German, Italian",
    "A key objective for Perseverance",
    "A number of European partners, including France",
    "About AIRS",
    "about the Cassini-Huygens mission visit",
    "Additional information about the Hubble Space Telescope",
    "Agenzia Spaziale Italiana (ASI)",
    "aims to understand the origin and evolution of",
    "AIRSAR is part of NASA's Earth Enterprise program",
    "and the instrument was built by Ball Aerospace and Technology Corp",
    "Aquarius will provide new insights",
    "are collaborating on proposals for",
    "are currently integrated aboard",
    "are international partners on the mission team",
    "are posted on the World Wide Web",
    "Arizona State University in Tempe leads the Psyche mission",
    "Arizona State University leads the mission",
    "as described by the Mars 2020 Science Definition Team",
    "As the first spacecraft ever to orbit Mercury",
    "ASTER is one of five Earth-observing instruments",
    "Astronomers study weather phenomena on other planets",
    "at Los Alamos National Laboratories",
    "at the Infrared Processing and Analysis Center",
    "at the Kennedy Space Center",
    "at the Russian Aviation and Space Agency",
    "Background information and educational context for the images can be found at",
    "built and manages",
    "built and operates the orbiter's Context Camera",
    "built and will manage operations of ",
    "built by Ball Aerospace Corporation",
    "built the orbiter and collaborates with JPL to operate it",
    "built the main body of the spacecraft",
    "built the science instrument",
    "built under the leadership of the Max Planck Institute for Solar System Research",
    "Caltech manages JPL for NASA",
    "camera was built by ",
    "camera was built by",
    "Cassini is a cooperative mission of NASA",
    "Ceres has an average diameter of about",
    "ChemCam was conceived, designed and built",
    "Color images from HiRISE combine information from detectors",
    "Complete HiRISE image products are available at",
    "completed its three-month prime mission",
    "conducts Hubble science operations",
    "contributed mission-enabling technology",
    "contributions by the German Aerospace Center (DLR) Institute of Planetary Research",
    "CRISM is one of six science instruments on NASA's Mars Reconnaissance Orbiter",
    "CRISM's mission: Find the spectral",
    "CRISM's mission:",
    "Curiosity is the centerpiece of NASA",
    "data are analyzed by a joint U.S.-Italian science team",
    "data received from Galileo are posted on the World Wide Web",
    "Data used to generate this animation was acquired by the Jovian Infrared",
    "Dawn entered orbit around Vesta on",
    "Dawn is a project of the directorate's Discovery Program",
    "Dawn is due to be captured",
    "Deep Space 1 completed its primary mission",
    "designed and built by",
    "designed and built the spacecraft",
    "designed and manufactured",
    "Deutsche Agentur fuer Raumfahrtangelegenheiten",
    "developed and managed by the",
    "developed and manages the Mars Pathfinder mission for NASA",
    "developed DAN in close cooperation with",
    "developed the DAN instrument",
    "Discovery Program of competitively selected missions",
    "During its flight, the Galileo spacecraft",
    "ended communications in November 2008",
    "facility is part of the School of Earth and Space Exploration",
    "For a complete list of acknowledgements",
    "For a complete list of acknowledgments",
    "For a complete list of Dawn mission participants",
    "For a complete list of mission participants",
    "For additional images visit the Cassini imaging team homepage",
    "For additional information about ",
    "For details about the DARPA Robotics",
    "for details on crediting THEMIS images",
    "For images and more information about Hubble",
    "For images visit the Cassini imaging team home page",
    "For information about NASA",
    "For information about the Galaxy Evolution Explorer",
    "For information regarding the use of images, see",
    "For more about Curiosity",
    "For more about Ingenuity",
    "For more about NASA",
    "For more about Opportunity",
    "For more about Perseverance",
    "For more about the Mars Exploration Program",
    "For more information about ",
    "For more information on ",
    "For more information, about ",
    "For more information, see",
    "For more information, visit",
    "For more information:",
    "for NASA's Office of Earth Science",
    "for NASA's Office of Space Science",
    "for NASA's Science Mission Directorate",
    "For publicly released image use, see ESA's Copyright Notice Images",
    "from the NASA Langley Research Center Atmospheric Science Data Center",
    "funded by the French national space agency",
    "funds the LDSD mission",
    "go.nasa.gov/ingenuity",
    "GRACE is a collaborative endeavor",
    "GRAIL's prime and extended science missions",
    "Herschel is a European Space Agency cornerstone mission",
    "http://www.spitzer.caltech.edu/"
    "Images from the High Resolution Imaging Science Experiment ",
    "images, multimedia and related materials",
    "in collaboration with the Russian Aviation and Space Agency",
    "information about the Galaxy Evolution Explorer are online at",
    "information about the Mars Reconnaissance Orbiter are available online at",
    "information about the QuikScat mission and observations is available at",
    "information on the GRACE mission is online",
    "InSight is part of NASA",
    "InSight, for Interior Exploration Using Seismic Investigations, Geodesy and Heat Transport",
    "Institute of Computer and Communication Network Engineering",
    "instrument was built by",
    "Investigators at Arizona State University",
    "is a collaborative endeavor involving",
    "is a cooperative project of NASA",
    "is a facility of the National Science",
    "is a mission of the European Space Agency",
    "is a partnership between NASA",
    "is a satellite mission designed to measure",
    "is an international endeavor with",
    "is based at NASA's Jet Propulsion Laboratory",
    "is based at the Space Science Institute",
    "is being prepared for launch",
    "is conducted by JPL for NASA",
    "is conducted by the Jet Propulsion Laboratory",
    "is funded by NASA",
    "is led by Los Alamos",
    "is led by JPL",
    "is led by Sally",
    "is managed by ",
    "is managed for NASA",
    "is managing the overall",
    "is on course to reach",
    "is one of six instruments on ",
    "is operated by the University of Arizona",
    "is operated by USRA"
    "is part of NASA's Mission to Planet Earth",
    "is part of America's larger Moon to Mars exploration",
    "is sponsored by NASA",
    "is the prime contractor for",
    "is the Principal Investigator",
    "is the project manager",
    "Jet Propulsion Laboratory for NASA",
    "Johnson Space Center, Houston, operate the science instruments",
    "jointly funded MARSIS",
    "jointly funded the instrument",
    "JPL built and will manage",
    "JPL contributed ",
    "JPL hosts the ",
    "JPL is a division of ",
    "JPL is an operating division of ",
    "JPL managed ",
    "JPL manages ",
    "JPL, a division of ",
    "JPL, which is managed for NASA ",
    "Juno aims to understand the origin",
    "Juno's primary goal is to",
    "JunoCam's raw images are available ",
    "leads the consortium that provided",
    "led by Sapienza University ",
    "Led by The Johns Hopkins University ",
    "Lockheed Martin Space Systems",
    "Malin Space Science Systems ",
    "manage the mission",
    "managed and controlled by ",
    "managed by JPL",
    "managed by NASA",
    "managed by the ",
    "managed by the Jet Propulsion Laboratory",
    "managed for NASA by ",
    "management of the mission is by",
    "manages Cassini for NASA",
    "manages JPL for NASA",
    "manages Kepler",
    "manages the Cassini mission ",
    "manages the Curiosity project",
    "manages the Deep Space Network",
    "manages the Diviner instrument",
    "manages the Galileo mission",
    "manages the InSight Project",
    "manages the Lunar Reconnaissance Orbiter",
    "manages the Mars",
    "manages the mission",
    "manages the project",
    "manages the Spitzer Space Telescope",
    "Mariner 4 was launched on",
    "Mariner 9 was launched on",
    "Mars 2020 is part of a larger program ",
    "Mars 2020 is targeted for launch in July",
    "Mars Global Surveyor entered Mars orbit on ",
    "Mars Science Laboratory project is using Curiosity",
    "Mars Surveyor Operations Project operates",
    "mars.nasa.gov/mars2020",
    "mars.nasa.gov/odyssey",
    "MESSENGER became the first spacecraft ever to orbit the planet Mercury",
    "mission is a joint project between",
    "mission is managed by",
    "mission is part of NASA",
    "Mission operations are conducted ",
    "mission's principal investigator, Edward Wright, is at UCLA",
    "More About the Mission",
    "More information about ",
    "More information can be found ",
    "More information for ",
    "More information is online at",
    "More information on Psyche",
    "More information on Spitzer",
    "More on NASA's ",
    "MSSS operates the camera from its facilities ",
    "Names shown on the globe are approved by",
    "NASA and Arizona State University",
    "NASA Astrobiology Institute",
    "NASA detects, tracks and characterizes ",
    "NASA Herschel Science Center, part of the Infrared Processing and Analysis Center at Caltech",
    "NASA managers have decided ",
    "NASA Science Mission Directorate",
    "nasa.gov/perseverance",
    "NASA's Jet Propulsion Laboratory manages",
    "NASA's Jet Propulsion Laboratory, a division of ",
    "NASA's Mars 2020 Perseverance mission will search",
    "NASA's Office of Space Science",
    "NASA's Planck Project Office is based at JPL",
    "NASA's Quick Scatterometer (QuikScat) spacecraft",
    "NASA's Science Mission Directorate",
    "NASA's Voyager 2 spacecraft launched",
    "NASA/JPL/MOLA",
    "NEAR was the first spacecraft launched in NASA's Discovery Program ",
    "NED is hosted at",
    "NEOWISE originated as a mission called WISE",
    "New Horizons is part of the New Frontiers Program",
    "NuSTAR's mission operations center",
    "of the Science Mission Directorate",
    "on behalf of NASA",
    "on the Galileo mission home page at",
    "Operated by Arizona",
    "operated by Malin",
    "operated by NASA",
    "operated by the University",
    "operates the European Space Agency's Mars Express mission",
    "operations and data processing will take place at",
    "operations are conducted",
    "operations are led by",
    "Opportunity completed its three-month",
    "Orbital Sciences Corporation of Dulles",
    "OSIRIS was built by a consortium led by",
    "Other imagery related to these new findings from ",
    "Other scientific partners include",
    "Over the course of its mission,",
    "part of NASA's Mission to Planet Earth program",
    "Philip Christensen at Arizona State  University",
    "Philip Christensen at Arizona State University",
    "Photojournal note:EarthKAM was formerly known as KidSat",
    "Please see the THEMIS Data Citation Note",
    "please visit our website",
    "Project will launch Curiosity",
    "provided the helicopter",
    "purpose of Curiosity's MAHLI camera is",
    "Ranger 7 was launched",
    "RapidScat measures Earth's ocean surface wind speed",
    "Rosetta NAVCAM image use is available under",
    "science team is located at ",
    "Scientists will use the images to ",
    "SDO is managed by NASA",
    "see the MESSENGER image use policy",
    "See the NEAR web page at",
    "SIR-C was developed by NASA",
    "Space Technology Mission Directorate",
    "spacecraft is managed by",
    "spacecraft was built by",
    "spacecraft was launched in",
    "Spirit has been analyzing",
    "STEREO, a two-year mission, launched",
    "Subsequent NASA missions, in cooperation with ESA",
    "Surrogate received support from",
    "The AFM was developed by ",
    "The Atlas V launch service is provided by ",
    "The broad spectral coverage and high spectral resolution of ASTER",
    "The conclusion of Dawn's mission operation",
    "The California Institute of Technology in Pasadena manages ",
    "The Cassini imaging team homepage",
    "The Cassini spacecraft ended its mission on",
    "The Cassini/Huygens spacecraft, launched from Earth in 1997",
    "The cooler was shipped to the",
    "the CRISM team includes expertise from",
    "the Deutsche Forschungsanstalt fuer Luft und Raumfahrt",
    "The DuAxel project is a technology demonstration",
    "the European Space Agency and the Italian Space Agency",
    "The final data transmission received from Pathfinder",
    "the first spacecraft ever to orbit Mercury",
    "the first spacecraft ever to orbit the planet Mercury",
    "The framing camera project is funded by",
    "The full image set for these observations can be seen",
    "The Galaxy Evolution Explorer launched on",
    "the German space agency, Deutsche Agentur fuer Raumfahrtangelegenheiten (DARA)",
    "The Gravity Recovery and Interior Laboratory (GRAIL) mission utilizes",
    "The High Resolution Imaging Science Experiment is operated by",
    "The Hubble Space Telescope is a project of international cooperation",
    "The Imager for Mars Pathfinder (IMP) was developed by",
    "the Italian space agency, Agenzia Spaziale Italiana (ASI)",
    "The Jet Propulsion Laboratory operates ",
    "The Jet Propulsion Laboratory, a division of ",
    "The Jet Propulsion Laboratory, Pasadena, CA manages ",
    "The Jet Propulsion Laboratory's Mars Surveyor Operations Project",
    "The Johns Hopkins University Applied Physics Laboratory in",
    "The JPL UAVSAR team",
    "The KidSat pilot program is sponsored",
    "The Low-Density Supersonic Decelerator Project is managed by JPL",
    "The Lunar Reconnaissance Orbiter Camera was designed to acquire data ",
    "The magnetometer team homepage is",
    "The main purpose of Curiosity's MAHLI camera is",
    "the major partner in science, operations and data processing",
    "The Mars 2020 mission is part of a larger program",
    "The Mars 2020 Perseverance mission is part of NASA",
    "The Mars Orbiter Camera can resolve",
    "The MESSENGER spacecraft is the first",
    "The MISR data were obtained from the NASA Langley",
    "The mission was competitively selected under NASA",
    "The mission is a joint effort between",
    "The National Oceanic and Atmospheric Administration has contributed",
    "The objective of SIR-A was to",
    "The Odyssey spacecraft has completed a full Mars year of observations",
    "The Odyssey spacecraft has spent over 15 years in orbit around Mars",
    "The probe is part of Phoenix",
    "The Southwest Research Institute, based in San Antonio, leads",
    "The spacecraft has been orbiting Mars since",
    "The THEMIS investigation is led by Dr",
    "The TLS technology from Curiosity",
    "The ultraviolet imaging spectrograph team home page",
    "The University of Arizona, Tucson, operates",
    "The University of California, Los Angeles, is responsible for",
    "The visual and infrared mapping spectrometer team homepage",
    "The website formerly known as KidSat was renamed",
    "The WISE spacecraft was put into hibernation",
    "These images are from MESSENGER, a NASA Discovery mission",
    "This array of indirect evidence of past life will be reported in the Aug",
    "This image and other images and data received from Galileo are posted",
    "This image was produced by DLR",
    "This mission will land Curiosity on Mars",
    "This research was carried out at JPL",
    "To learn more about the mission",
    "To see images of KidSat",
    "To see updates on the efforts to free the Spirit rover",
    "To see what the raw MOC image data look like",
    "TOPEX/Poseidon project web page at",
    "UAVSAR is part of NASA",
    "UCLA is home institution of Diviner's principal investigator",
    "UCLA is responsible for overall Dawn mission science",
    "under a cooperative agreement with",
    "under consideration by NASA",
    "under contract to JPL",
    "under the contracting authority",
    "under the leadership of the Max Planck Institute",
    "visual and infrared mapping spectrometer team homepage",
    "Voyager 1 spacecraft launched",
    "was built and is managed by ",
    "was built by a consortium",
    "was built by Ball",
    "was built by Japan",
    "was built by JPL",
    "was built by the Lockheed",
    "was built by the Space Dynamics Laboratory",
    "was built in Japan",
    "was built jointly by JPL and NASA",
    "was captured by the mission's imaging camera",
    "was conceived, designed and built by",
    "was designed, developed and assembled at JPL",
    "was developed and built by",
    "was developed and is operated by",
    "was developed by Arizona State University",
    "was developed by the Dornier and Alenia Spazio companies",
    "was developed by the University of Arizona",
    "was developed jointly by NASA",
    "was developed, built and tested by",
    "was launched from Vandenberg Air Force Base",
    "was provided by Arizona State University",
    "was provided by the Italian Space Agency",
    "was provided by the University of Arizona",
    "were designed, developed and assembled at JPL",
    "were retrieved from the Planetary Data System's Cassini archives",
    "WFIRST is managed at",
    "which is managed by the J",
    "which provided the high-energy neutron detector",
    "which provided the neutron spectrometer",
    "which was built by Ball",
    "which was designed and built by JPL",
    "will provide global color and stereo coverage",
    "WISE is an all-sky survey",
    "With its 14 spectral bands from the visible to",
    "with its industrial partner, Lockheed",
    "with science instruments provided by consortia of European institutes",
    "with significant participation from NASA",
    "with significant contributions from the Max Planck Institute",
    "working in collaboration with Malin",
#     "a division of the California Institute of Technology",
#     "and links to data from other missions",
#     "as part of a NASA-funded",
#     "During a prime mission lasting nearly two years",
#     "For additional information about",
#     "For additional information on",
#     "For more information about",
#     "For more information:",
#     "has been prepared for launch",
#     "has not been radiometrically nor geometrically calibrated",
#     "Infrared Processing and Analysis Center at the California Institute of Technology",
#     "Initial image processing and calibration by THEMIS team members",
#     "is being assembled and tested for launch",
#     "Malin Space Science Systems, San Diego",
#     "MISR observes the daylit Earth",
#     "MISR views Earth with nine cameras",
#     "NASA will launch",
#     "on the European Space Agency's Mars Express orbiter",
#     "Opportunity landed on",
#     "part of the Infrared Processing and Analysis Center at the California Institute of Technology",
#     "please visit",
#     "Researchers have been using ",
#     "slated for launch in",
#     "team at NASA",
#     "The Cassini orbiter has revealed many surprises",
#     "The THEMIS VIS camera contains 5 filters",
#     "The THEMIS VIS camera is capable of capturing color images",
#     "The THEMIS VIS camera is capable of capturing color images",
#     "THEMIS visual image has not been radiometrically",
#     "These images were acquired by the Mars Orbiter Camera",
#     "These images were prepared by",
#     "This color treatment is the result of a collaboration between",
#     "This image taken by the hazard",
#     "This image was acquired as a high-resolution targeted color observation",
#     "This image was acquired as a high-resolution",
#     "This image was acquired as part of MDIS's",
#     "This image was acquired as part of the MDIS",
#     "this THEMIS visual image has not been radiometrically",
#     "To learn more about",
#     "Welcome to another brief interval of THEMIS Images as Art",
#     "which took this image",
]

################################################################################
